In [1]:
import os
import subprocess
import numpy as np
import pandas as pd

In [2]:
# This snippet assumes that you run setup first

# This code lists objects in your Google Bucket

# Get the bucket name
my_bucket = os.getenv('WORKSPACE_BUCKET')

# List objects in the bucket
print(subprocess.check_output(f"gsutil ls -r {my_bucket}", shell=True).decode('utf-8'))

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr10_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr10_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr11_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr11_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr12_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr12_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr13_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr13_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr14_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr14_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr15_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr15_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr16_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr16_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr17_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr17_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr18_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr18_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr19_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr19_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr1_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr1_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr20_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr20_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr21_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr21_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr22_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr22_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr2_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr2_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr3_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr3_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr4_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr4_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr5_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr5_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr6_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr6_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr7_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr7_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr8_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr8_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr9_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr9_allind.rds

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/:

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/:

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/:

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/condition_22769885/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/condition_22769885/condition_22769885_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/condition_27096384/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/condition_27096384/condition_27096384_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/condition_32581449/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/condition_32581449/condition_32581449_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/condition_79586544/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/condition_79586544/condition_79586544_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/condition_84516414/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/condition_84516414/condition_84516414_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/condition_93775608/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/condition_93775608/condition_93775608_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/drug_45376339/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/drug_45376339/drug_45376339_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/drug_97024772/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/drug_97024772/drug_97024772_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/measurement_79586544/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/measurement_79586544/measurement_79586544_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/observation_00963032/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/observation_00963032/observation_00963032_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/person_71011318/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/person_71011318/person_71011318_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/procedure_02762000/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/procedure_02762000/procedure_02762000_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/procedure_15254378/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/procedure_15254378/procedure_15254378_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/procedure_47740110/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/procedure_47740110/procedure_47740110_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/procedure_79586544/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/procedure_79586544/procedure_79586544_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/:

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_04318565/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_04318565/condition_04318565_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_57829836/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_57829836/condition_57829836_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_66443155/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_66443155/condition_66443155_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_82100016/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_82100016/condition_82100016_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_87448626/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_87448626/condition_87448626_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_93801899/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_93801899/condition_93801899_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_97626158/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_97626158/condition_97626158_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_99489694/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_99489694/condition_99489694_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/measurement_05885865/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/measurement_05885865/measurement_05885865_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/measurement_60313913/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/measurement_60313913/measurement_60313913_000000000000.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/measurement_60313913/measurement_60313913_000000000001.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/measurement_60313913/measurement_60313913_000000000002.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/measurement_60313913/measurement_60313913_000000000003.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/measurement_60313913/measurement_60313913_000000000004.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/measurement_60313913/measurement_60313913_000000000005.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/measurement_60313913/measurement_60313913_000000000006.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/measurement_60313913/measurement_60313913_000000000007.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/measurement_60313913/measurement_60313913_000000000008.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/measurement_60313913/measurement_60313913_000000000009.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/observation_04318565/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/observation_04318565/observation_04318565_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/observation_65805338/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/observation_65805338/observation_65805338_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/person_51780597/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/person_51780597/person_51780597_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/procedure_04318565/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/procedure_04318565/procedure_04318565_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/procedure_47173302/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/procedure_47173302/procedure_47173302_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/procedure_93801899/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/procedure_93801899/procedure_93801899_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/:

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/condition_57829836/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/condition_57829836/condition_57829836_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/condition_87448626/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/condition_87448626/condition_87448626_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/condition_97626158/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/condition_97626158/condition_97626158_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/measurement_05885865/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/measurement_05885865/measurement_05885865_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/observation_65805338/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/observation_65805338/observation_65805338_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/person_51780597/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/person_51780597/person_51780597_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/procedure_47173302/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/procedure_47173302/procedure_47173302_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/survey_16801330/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/survey_16801330/survey_16801330_000000000000.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/survey_16801330/survey_16801330_000000000001.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/survey_16801330/survey_16801330_000000000002.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/survey_16801330/survey_16801330_000000000003.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/survey_16801330/survey_16801330_000000000004.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/survey_16801330/survey_16801330_000000000005.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/survey_16801330/survey_16801330_000000000006.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/survey_16801330/survey_16801330_000000000007.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/survey_16801330/survey_16801330_000000000008.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/survey_16801330/survey_16801330_000000000009.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/survey_28116944/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/survey_28116944/survey_28116944_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/survey_81293648/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/survey_81293648/survey_81293648_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250213/:

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250213/condition_32581449/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250213/condition_32581449/condition_32581449_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250213/condition_79586544/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250213/condition_79586544/condition_79586544_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250213/condition_84516414/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250213/condition_84516414/condition_84516414_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250213/condition_93775608/:

In [28]:
%%bash

#!/bin/bash

# Define an array of disease names
diseases=("asthma" "atrial_fibrilation" "breast_cancer" "ckd" "coronary_heart_disease" "hypercholesterolemia"
          "prostate_cancer" "t1d" "t2d")


# Construct the GCS base path
gs_path="gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink"

# Temporary directory to store intermediate files
temp_dir="./temp_combined_files"
mkdir -p "$temp_dir"

# Loop through each disease
for disease in "${diseases[@]}"; do
    echo "Processing Disease: ${disease}"

    # Log file per disease
    log_file="combine_chr_${disease}_log.txt"
    exec > >(tee -a "$log_file") 2>&1

    # Clear file_paths array for each disease
    file_paths=()

    for chromo in {1..22}; do
        file_name="PRS_chr${chromo}_${disease}.profile"
        local_path="${temp_dir}/${file_name}"

        # Try to copy the file from GCS
        if gsutil cp "${gs_path}/${file_name}" "$local_path"; then
            file_paths+=("$local_path")
        else
            echo "Warning: File not found for chr${chromo} - ${file_name}"
        fi
    done

    if [[ ${#file_paths[@]} -eq 0 ]]; then
        echo "No files found for ${disease}, skipping..."
        continue
    fi

    # Combine files using AWK
    awk '
    
        BEGIN { OFS = "," }  # Set output separator to tab
        
        FNR == 1 && NR == 1 { print $2, $4, $5, $6; next }
        FNR == 1 { next }  # Skip headers from all but first file
        {
            cnt[$2] += $4;
            cnt2[$2] += $5;
            score[$2] += $6;
        }
        END {
            for (i in score) {
                print i, cnt[i], cnt2[i], score[i];
            }
        }
    ' "${file_paths[@]}" > "${temp_dir}/combined_${disease}.txt"

    # Upload the combined file to GCS
    gsutil cp "${temp_dir}/combined_${disease}.txt" "gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/data/"

    echo "Done processing ${disease}"
done

Processing Disease: asthma
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr1_asthma.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr2_asthma.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr3_asthma.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr4_asthma.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr5_asthma.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr6_asthma.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr7_asthma.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr8_asthma.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr9_asthma.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr10_asthma.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr11_asthma.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr12_asthma.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr13_asthma.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr14_asthma.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr15_asthma.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr16_asthma.profile...
/ [1 files][ 19.1 MiB/ 19.1 MiB]
Operation completed over 1 objects/19.1 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr17_asthma.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr18_asthma.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr19_asthma.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr20_asthma.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr21_asthma.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr22_asthma.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying file://./temp_combined_files/combined_asthma.txt [Content-Type=text/plain]...
| [1 files][ 13.8 MiB/ 13.8 MiB]
Operation completed over 1 objects/13.8 MiB.
Done processing asthma
Processing Disease: atrial_fibrilation
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr1_atrial_fibrilation.profile...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr2_atrial_fibrilation.profile...
/ [1 files][ 18.1 MiB/ 18.1 MiB]
Operation completed over 1 objects/18.1 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr3_atrial_fibrilation.profile...
/ [1 files][ 18.1 MiB/ 18.1 MiB]
Operation completed over 1 objects/18.1 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr4_atrial_fibrilation.profile...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr5_atrial_fibrilation.profile...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr6_atrial_fibrilation.profile...
/ [1 files][ 17.8 MiB/ 17.8 MiB]
Operation completed over 1 objects/17.8 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr7_atrial_fibrilation.profile...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr8_atrial_fibrilation.profile...
/ [1 files][ 18.2 MiB/ 18.2 MiB]

Operation completed over 1 objects/18.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr9_atrial_fibrilation.profile...
/ [1 files][ 18.0 MiB/ 18.0 MiB]
Operation completed over 1 objects/18.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr10_atrial_fibrilation.profile...
/ [1 files][ 18.1 MiB/ 18.1 MiB]
Operation completed over 1 objects/18.1 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr11_atrial_fibrilation.profile...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr12_atrial_fibrilation.profile...
/ [1 files][ 18.1 MiB/ 18.1 MiB]
Operation completed over 1 objects/18.1 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr13_atrial_fibrilation.profile...
/ [1 files][ 17.8 MiB/ 17.8 MiB]
Operation completed over 1 objects/17.8 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr14_atrial_fibrilation.profile...
/ [1 files][ 18.1 MiB/ 18.1 MiB]
Operation completed over 1 objects/18.1 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr15_atrial_fibrilation.profile...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr16_atrial_fibrilation.profile...
/ [1 files][ 17.8 MiB/ 17.8 MiB]
Operation completed over 1 objects/17.8 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr17_atrial_fibrilation.profile...
/ [1 files][ 17.8 MiB/ 17.8 MiB]
Operation completed over 1 objects/17.8 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr18_atrial_fibrilation.profile...
/ [1 files][ 18.1 MiB/ 18.1 MiB]
Operation completed over 1 objects/18.1 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr19_atrial_fibrilation.profile...
/ [1 files][ 17.8 MiB/ 17.8 MiB]
Operation completed over 1 objects/17.8 MiB.
CommandException: No URLs matched: gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr20_atrial_fibrilation.profile
Warning: File not found for chr20 - PRS_chr20_atrial_fibrilation.profile
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr21_atrial_fibrilation.profile...
/ [1 files][ 17.8 MiB/ 17.8 MiB]
Operation completed over 1 objects/17.8 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr22_atrial_fibrilation.profile...
/ [1 files][ 17.8 MiB/ 17.8 MiB]
Operation completed over 1 objects/17.8 MiB.
Copying file://./temp_combined_files/combined_atrial_fibrilation.txt [Content-Type=text/plain]...
/ [1 files][  9.8 MiB/  9.8 MiB]
Operation completed over 1 objects/9.8 MiB.
Done processing atrial_fibrilation
Processing Disease: breast_cancer
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr1_breast_cancer.profile...
/ [1 files][ 18.6 MiB/ 18.6 MiB]
Operation completed over 1 objects/18.6 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr2_breast_cancer.profile...
/ [1 files][ 18.6 MiB/ 18.6 MiB]
Operation completed over 1 objects/18.6 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr3_breast_cancer.profile...
/ [1 files][ 18.4 MiB/ 18.4 MiB]
Operation completed over 1 objects/18.4 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr4_breast_cancer.profile...
/ [1 files][ 18.9 MiB/ 18.9 MiB]
Operation completed over 1 objects/18.9 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr5_breast_cancer.profile...
/ [1 files][ 18.9 MiB/ 18.9 MiB]
Operation completed over 1 objects/18.9 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr6_breast_cancer.profile...
/ [1 files][ 18.5 MiB/ 18.5 MiB]
Operation completed over 1 objects/18.5 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr7_breast_cancer.profile...
/ [1 files][ 18.5 MiB/ 18.5 MiB]
Operation completed over 1 objects/18.5 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr8_breast_cancer.profile...
/ [1 files][ 18.7 MiB/ 18.7 MiB]
Operation completed over 1 objects/18.7 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr9_breast_cancer.profile...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr10_breast_cancer.profile...
/ [1 files][ 18.4 MiB/ 18.4 MiB]
Operation completed over 1 objects/18.4 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr11_breast_cancer.profile...
/ [1 files][ 18.9 MiB/ 18.9 MiB]
Operation completed over 1 objects/18.9 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr12_breast_cancer.profile...
/ [1 files][ 18.6 MiB/ 18.6 MiB]
Operation completed over 1 objects/18.6 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr13_breast_cancer.profile...
/ [1 files][ 17.8 MiB/ 17.8 MiB]
Operation completed over 1 objects/17.8 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr14_breast_cancer.profile...
/ [1 files][ 18.4 MiB/ 18.4 MiB]
Operation completed over 1 objects/18.4 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr15_breast_cancer.profile...
/ [1 files][ 18.6 MiB/ 18.6 MiB]
Operation completed over 1 objects/18.6 MiB.

Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr16_breast_cancer.profile...
- [1 files][ 18.6 MiB/ 18.6 MiB]
Operation completed over 1 objects/18.6 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr17_breast_cancer.profile...
/ [1 files][ 18.5 MiB/ 18.5 MiB]
Operation completed over 1 objects/18.5 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr18_breast_cancer.profile...
/ [1 files][ 18.4 MiB/ 18.4 MiB]
Operation completed over 1 objects/18.4 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr19_breast_cancer.profile...
/ [1 files][ 18.7 MiB/ 18.7 MiB]
Operation completed over 1 objects/18.7 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr20_breast_cancer.profile...
/ [1 files][ 17.9 MiB/ 17.9 MiB]
Operation completed over 1 objects/17.9 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr21_breast_cancer.profile...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr22_breast_cancer.profile...
/ [1 files][ 18.7 MiB/ 18.7 MiB]
Operation completed over 1 objects/18.7 MiB.
Copying file://./temp_combined_files/combined_breast_cancer.txt [Content-Type=text/plain]...
/ [1 files][ 10.3 MiB/ 10.3 MiB]
Operation completed over 1 objects/10.3 MiB.
Done processing breast_cancer
Processing Disease: ckd
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr1_ckd.profile...
/ [1 files][ 19.1 MiB/ 19.1 MiB]
Operation completed over 1 objects/19.1 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr2_ckd.profile...
/ [1 files][ 19.2 MiB/ 19.2 MiB]
Operation completed over 1 objects/19.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr3_ckd.profile...
/ [1 files][ 19.1 MiB/ 19.1 MiB]
Operation completed over 1 objects/19.1 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr4_ckd.profile...
/ [1 files][ 19.2 MiB/ 19.2 MiB]
Operation completed over 1 objects/19.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr5_ckd.profile...
/ [1 files][ 19.2 MiB/ 19.2 MiB]
Operation completed over 1 objects/19.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr6_ckd.profile...
/ [1 files][ 19.1 MiB/ 19.1 MiB]
Operation completed over 1 objects/19.1 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr7_ckd.profile...
/ [1 files][ 19.1 MiB/ 19.1 MiB]
Operation completed over 1 objects/19.1 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr8_ckd.profile...
/ [1 files][ 19.1 MiB/ 19.1 MiB]
Operation completed over 1 objects/19.1 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr9_ckd.profile...
/ [1 files][ 19.2 MiB/ 19.2 MiB]
Operation completed over 1 objects/19.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr10_ckd.profile...
/ [1 files][ 19.2 MiB/ 19.2 MiB]
Operation completed over 1 objects/19.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr11_ckd.profile...
/ [1 files][ 19.1 MiB/ 19.1 MiB]
Operation completed over 1 objects/19.1 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr12_ckd.profile...
/ [1 files][ 19.1 MiB/ 19.1 MiB]
Operation completed over 1 objects/19.1 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr13_ckd.profile...
/ [1 files][ 19.1 MiB/ 19.1 MiB]
Operation completed over 1 objects/19.1 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr14_ckd.profile...
/ [1 files][ 19.3 MiB/ 19.3 MiB]
Operation completed over 1 objects/19.3 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr15_ckd.profile...
/ [1 files][ 19.2 MiB/ 19.2 MiB]
Operation completed over 1 objects/19.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr16_ckd.profile...
/ [1 files][ 19.3 MiB/ 19.3 MiB]
Operation completed over 1 objects/19.3 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr17_ckd.profile...
/ [1 files][ 19.1 MiB/ 19.1 MiB]
Operation completed over 1 objects/19.1 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr18_ckd.profile...
/ [1 files][ 19.2 MiB/ 19.2 MiB]
Operation completed over 1 objects/19.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr19_ckd.profile...
/ [1 files][ 19.2 MiB/ 19.2 MiB]
Operation completed over 1 objects/19.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr20_ckd.profile...
/ [1 files][ 19.1 MiB/ 19.1 MiB]
Operation completed over 1 objects/19.1 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr21_ckd.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr22_ckd.profile...
/ [1 files][ 19.1 MiB/ 19.1 MiB]
Operation completed over 1 objects/19.1 MiB.
Copying file://./temp_combined_files/combined_ckd.txt [Content-Type=text/plain]...
| [1 files][ 13.6 MiB/ 13.6 MiB]
Operation completed over 1 objects/13.6 MiB.
Done processing ckd
Processing Disease: coronary_heart_disease
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr1_coronary_heart_disease.profile...

/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr2_coronary_heart_disease.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr3_coronary_heart_disease.profile...
/ [1 files][ 19.3 MiB/ 19.3 MiB]
Operation completed over 1 objects/19.3 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr4_coronary_heart_disease.profile...
/ [1 files][ 19.3 MiB/ 19.3 MiB]
Operation completed over 1 objects/19.3 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr5_coronary_heart_disease.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr6_coronary_heart_disease.profile...
/ [1 files][ 19.3 MiB/ 19.3 MiB]
Operation completed over 1 objects/19.3 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr7_coronary_heart_disease.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr8_coronary_heart_disease.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr9_coronary_heart_disease.profile...
/ [1 files][ 19.3 MiB/ 19.3 MiB]
Operation completed over 1 objects/19.3 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr10_coronary_heart_disease.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr11_coronary_heart_disease.profile...
/ [1 files][ 19.3 MiB/ 19.3 MiB]
Operation completed over 1 objects/19.3 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr12_coronary_heart_disease.profile...
/ [1 files][ 19.3 MiB/ 19.3 MiB]
Operation completed over 1 objects/19.3 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr13_coronary_heart_disease.profile...
/ [1 files][ 19.1 MiB/ 19.1 MiB]
Operation completed over 1 objects/19.1 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr14_coronary_heart_disease.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr15_coronary_heart_disease.profile...
/ [1 files][ 19.3 MiB/ 19.3 MiB]
Operation completed over 1 objects/19.3 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr16_coronary_heart_disease.profile...
/ [1 files][ 19.3 MiB/ 19.3 MiB]
Operation completed over 1 objects/19.3 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr17_coronary_heart_disease.profile...
/ [1 files][ 19.3 MiB/ 19.3 MiB]
Operation completed over 1 objects/19.3 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr18_coronary_heart_disease.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr19_coronary_heart_disease.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr20_coronary_heart_disease.profile...
/ [1 files][ 19.3 MiB/ 19.3 MiB]
Operation completed over 1 objects/19.3 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr21_coronary_heart_disease.profile...
/ [1 files][ 19.2 MiB/ 19.2 MiB]
Operation completed over 1 objects/19.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr22_coronary_heart_disease.profile...
/ [1 files][ 18.7 MiB/ 18.7 MiB]
Operation completed over 1 objects/18.7 MiB.
Copying file://./temp_combined_files/combined_coronary_heart_disease.txt [Content-Type=text/plain]...
| [1 files][ 13.4 MiB/ 13.4 MiB]
Operation completed over 1 objects/13.4 MiB.
Done processing coronary_heart_disease
Processing Disease: hypercholesterolemia
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr1_hypercholesterolemia.profile...
/ [1 files][ 19.3 MiB/ 19.3 MiB]
Operation completed over 1 objects/19.3 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr2_hypercholesterolemia.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr3_hypercholesterolemia.profile...
/ [1 files][ 19.2 MiB/ 19.2 MiB]
Operation completed over 1 objects/19.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr4_hypercholesterolemia.profile...
/ [1 files][ 19.3 MiB/ 19.3 MiB]
Operation completed over 1 objects/19.3 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr5_hypercholesterolemia.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr6_hypercholesterolemia.profile...
/ [1 files][ 19.3 MiB/ 19.3 MiB]
Operation completed over 1 objects/19.3 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr7_hypercholesterolemia.profile...
/ [1 files][ 19.3 MiB/ 19.3 MiB]
Operation completed over 1 objects/19.3 MiB.

Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr8_hypercholesterolemia.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr9_hypercholesterolemia.profile...
/ [1 files][ 19.1 MiB/ 19.1 MiB]
Operation completed over 1 objects/19.1 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr10_hypercholesterolemia.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr11_hypercholesterolemia.profile...
/ [1 files][ 19.3 MiB/ 19.3 MiB]
Operation completed over 1 objects/19.3 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr12_hypercholesterolemia.profile...
/ [1 files][ 19.1 MiB/ 19.1 MiB]
Operation completed over 1 objects/19.1 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr13_hypercholesterolemia.profile...
/ [1 files][ 19.1 MiB/ 19.1 MiB]
Operation completed over 1 objects/19.1 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr14_hypercholesterolemia.profile...
/ [1 files][ 19.3 MiB/ 19.3 MiB]
Operation completed over 1 objects/19.3 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr15_hypercholesterolemia.profile...
/ [1 files][ 19.1 MiB/ 19.1 MiB]
Operation completed over 1 objects/19.1 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr16_hypercholesterolemia.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr17_hypercholesterolemia.profile...
/ [1 files][ 19.3 MiB/ 19.3 MiB]
Operation completed over 1 objects/19.3 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr18_hypercholesterolemia.profile...
/ [1 files][ 19.2 MiB/ 19.2 MiB]
Operation completed over 1 objects/19.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr19_hypercholesterolemia.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr20_hypercholesterolemia.profile...
/ [1 files][ 19.3 MiB/ 19.3 MiB]
Operation completed over 1 objects/19.3 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr21_hypercholesterolemia.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr22_hypercholesterolemia.profile...
/ [1 files][ 19.1 MiB/ 19.1 MiB]
Operation completed over 1 objects/19.1 MiB.
Copying file://./temp_combined_files/combined_hypercholesterolemia.txt [Content-Type=text/plain]...
\ [1 files][ 12.3 MiB/ 12.3 MiB]
Operation completed over 1 objects/12.3 MiB.
Done processing hypercholesterolemia
Processing Disease: prostate_cancer
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr1_prostate_cancer.profile...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr2_prostate_cancer.profile...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr3_prostate_cancer.profile...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr4_prostate_cancer.profile...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr5_prostate_cancer.profile...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr6_prostate_cancer.profile...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr7_prostate_cancer.profile...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr8_prostate_cancer.profile...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr9_prostate_cancer.profile...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr10_prostate_cancer.profile...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr11_prostate_cancer.profile...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr12_prostate_cancer.profile...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr13_prostate_cancer.profile...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr14_prostate_cancer.profile...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.

Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr15_prostate_cancer.profile...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr16_prostate_cancer.profile...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr17_prostate_cancer.profile...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr18_prostate_cancer.profile...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr19_prostate_cancer.profile...
/ [1 files][ 18.0 MiB/ 18.0 MiB]
Operation completed over 1 objects/18.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr20_prostate_cancer.profile...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr21_prostate_cancer.profile...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr22_prostate_cancer.profile...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.
Copying file://./temp_combined_files/combined_prostate_cancer.txt [Content-Type=text/plain]...
| [1 files][  9.6 MiB/  9.6 MiB]
Operation completed over 1 objects/9.6 MiB.
Done processing prostate_cancer
Processing Disease: t1d
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr1_t1d.profile...
/ [1 files][ 17.8 MiB/ 17.8 MiB]
Operation completed over 1 objects/17.8 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr2_t1d.profile...
/ [1 files][ 17.8 MiB/ 17.8 MiB]
Operation completed over 1 objects/17.8 MiB.
CommandException: No URLs matched: gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr3_t1d.profile
Warning: File not found for chr3 - PRS_chr3_t1d.profile
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr4_t1d.profile...
/ [1 files][ 17.8 MiB/ 17.8 MiB]
Operation completed over 1 objects/17.8 MiB.
CommandException: No URLs matched: gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr5_t1d.profile
Warning: File not found for chr5 - PRS_chr5_t1d.profile
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr6_t1d.profile...
/ [1 files][ 17.8 MiB/ 17.8 MiB]
Operation completed over 1 objects/17.8 MiB.
CommandException: No URLs matched: gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr7_t1d.profile
Warning: File not found for chr7 - PRS_chr7_t1d.profile
CommandException: No URLs matched: gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr8_t1d.profile
Warning: File not found for chr8 - PRS_chr8_t1d.profile
CommandException: No URLs matched: gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr9_t1d.profile
Warning: File not found for chr9 - PRS_chr9_t1d.profile
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr10_t1d.profile...
/ [1 files][ 17.8 MiB/ 17.8 MiB]
Operation completed over 1 objects/17.8 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr11_t1d.profile...
/ [1 files][ 17.8 MiB/ 17.8 MiB]
Operation completed over 1 objects/17.8 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr12_t1d.profile...
/ [1 files][ 17.8 MiB/ 17.8 MiB]
Operation completed over 1 objects/17.8 MiB.
CommandException: No URLs matched: gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr13_t1d.profile
Warning: File not found for chr13 - PRS_chr13_t1d.profile
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr14_t1d.profile...
/ [1 files][ 17.8 MiB/ 17.8 MiB]
Operation completed over 1 objects/17.8 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr15_t1d.profile...
/ [1 files][ 17.8 MiB/ 17.8 MiB]
Operation completed over 1 objects/17.8 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr16_t1d.profile...
/ [1 files][ 17.8 MiB/ 17.8 MiB]
Operation completed over 1 objects/17.8 MiB.
CommandException: No URLs matched: gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr17_t1d.profile
Warning: File not found for chr17 - PRS_chr17_t1d.profile
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr18_t1d.profile...
/ [1 files][ 17.8 MiB/ 17.8 MiB]
Operation completed over 1 objects/17.8 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr19_t1d.profile...
/ [1 files][ 17.8 MiB/ 17.8 MiB]
Operation completed over 1 objects/17.8 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr20_t1d.profile...
/ [1 files][ 17.8 MiB/ 17.8 MiB]
Operation completed over 1 objects/17.8 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr21_t1d.profile...
/ [1 files][ 17.8 MiB/ 17.8 MiB]
Operation completed over 1 objects/17.8 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr22_t1d.profile...
/ [1 files][ 17.8 MiB/ 17.8 MiB]
Operation completed over 1 objects/17.8 MiB.
Copying file://./temp_combined_files/combined_t1d.txt [Content-Type=text/plain]...
| [1 files][  9.3 MiB/  9.3 MiB]
Operation completed over 1 objects/9.3 MiB.
Done processing t1d
Processing Disease: t2d
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr1_t2d.profile...
/ [1 files][ 19.1 MiB/ 19.1 MiB]
Operation completed over 1 objects/19.1 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr2_t2d.profile...

/ [1 files][ 19.3 MiB/ 19.3 MiB]
Operation completed over 1 objects/19.3 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr3_t2d.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr4_t2d.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr5_t2d.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr6_t2d.profile...
/ [1 files][ 19.1 MiB/ 19.1 MiB]
Operation completed over 1 objects/19.1 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr7_t2d.profile...
/ [1 files][ 19.1 MiB/ 19.1 MiB]
Operation completed over 1 objects/19.1 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr8_t2d.profile...
/ [1 files][ 19.2 MiB/ 19.2 MiB]
Operation completed over 1 objects/19.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr9_t2d.profile...
/ [1 files][ 19.1 MiB/ 19.1 MiB]
Operation completed over 1 objects/19.1 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr10_t2d.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr11_t2d.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr12_t2d.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr13_t2d.profile...
/ [1 files][ 19.1 MiB/ 19.1 MiB]
Operation completed over 1 objects/19.1 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr14_t2d.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr15_t2d.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr16_t2d.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr17_t2d.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr18_t2d.profile...
/ [1 files][ 19.1 MiB/ 19.1 MiB]
Operation completed over 1 objects/19.1 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr19_t2d.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr20_t2d.profile...
/ [1 files][ 19.2 MiB/ 19.2 MiB]
Operation completed over 1 objects/19.2 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr21_t2d.profile...
/ [1 files][ 19.1 MiB/ 19.1 MiB]
Operation completed over 1 objects/19.1 MiB.
Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr22_t2d.profile...
/ [1 files][ 19.1 MiB/ 19.1 MiB]
Operation completed over 1 objects/19.1 MiB.
Copying file://./temp_combined_files/combined_t2d.txt [Content-Type=text/plain]...
| [1 files][ 13.8 MiB/ 13.8 MiB]
Operation completed over 1 objects/13.8 MiB.
Done processing t2d

In [27]:
name_of_file_in_bucket = 'combined_asthma.txt'

# copy csv file from the bucket to the current working space
os.system(f"gsutil cp '{my_bucket}/data/{name_of_file_in_bucket}' .")

my_dataframe = pd.read_csv(name_of_file_in_bucket) #, usecols=[0,3])
my_dataframe.head()

Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/data/combined_asthma.txt...
/ [1 files][ 13.0 MiB/ 13.0 MiB]
Operation completed over 1 objects/13.0 MiB.

       IID     CNT   CNT2     SCORE
0  8730010  325724  93265  0.000003
1  4141984  325722  79823  0.000001
2  2723508  325802  78635  0.000002
3  2473401  325724  87996  0.000002
4  1039754  325752  80550  0.000001

In [11]:
name_of_file_in_bucket = 'PRS_chr14_asthma.profile'

# copy csv file from the bucket to the current working space
os.system(f"gsutil cp '{my_bucket}/dsub/plink/{name_of_file_in_bucket}' .")

my_dataframe = pd.read_csv(name_of_file_in_bucket)
my_dataframe.head()

Copying gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/dsub/plink/PRS_chr14_asthma.profile...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.

       FID       IID  PHENO    CNT   CNT2    SCORE
0     0   1000000     -9  66216  18818 2.11456e-06
1     0   1000004     -9  66222  16269 1.36893e-06
2     0   1000033     -9  66200  15989 9.01139e-07
3     0   1000039     -9  66180  18831 2.09624e-06
4     0   1000042     -9  66212  19191 1.97307e-06

In [18]:
# This snippet assumes that you run setup first

# This code lists objects in your Google Bucket

# Get the bucket name
my_bucket = os.getenv('WORKSPACE_BUCKET')

# List objects in the bucket
print(subprocess.check_output(f"gsutil ls -r {my_bucket}", shell=True).decode('utf-8'))

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr10_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr10_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr11_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr11_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr12_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr12_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr13_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr13_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr14_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr14_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr15_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr15_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr16_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr16_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr17_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr17_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr18_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr18_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr19_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr19_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr1_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr1_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr20_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr20_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr21_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr21_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr22_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr22_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr2_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr2_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr3_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr3_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr4_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr4_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr5_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr5_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr6_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr6_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr7_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr7_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr8_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr8_allind.rds
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr9_allind.bk
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bigsnpr_backing/chr9_allind.rds

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/:

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/:

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/:

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/condition_22769885/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/condition_22769885/condition_22769885_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/condition_27096384/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/condition_27096384/condition_27096384_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/condition_32581449/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/condition_32581449/condition_32581449_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/condition_79586544/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/condition_79586544/condition_79586544_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/condition_84516414/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/condition_84516414/condition_84516414_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/condition_93775608/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/condition_93775608/condition_93775608_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/drug_45376339/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/drug_45376339/drug_45376339_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/drug_97024772/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/drug_97024772/drug_97024772_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/measurement_79586544/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/measurement_79586544/measurement_79586544_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/observation_00963032/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/observation_00963032/observation_00963032_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/person_71011318/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/person_71011318/person_71011318_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/procedure_02762000/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/procedure_02762000/procedure_02762000_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/procedure_15254378/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/procedure_15254378/procedure_15254378_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/procedure_47740110/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/procedure_47740110/procedure_47740110_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/procedure_79586544/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250204/procedure_79586544/procedure_79586544_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/:

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_04318565/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_04318565/condition_04318565_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_57829836/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_57829836/condition_57829836_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_66443155/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_66443155/condition_66443155_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_82100016/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_82100016/condition_82100016_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_87448626/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_87448626/condition_87448626_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_93801899/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_93801899/condition_93801899_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_97626158/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_97626158/condition_97626158_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_99489694/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/condition_99489694/condition_99489694_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/measurement_05885865/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/measurement_05885865/measurement_05885865_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/measurement_60313913/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/measurement_60313913/measurement_60313913_000000000000.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/measurement_60313913/measurement_60313913_000000000001.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/measurement_60313913/measurement_60313913_000000000002.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/measurement_60313913/measurement_60313913_000000000003.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/measurement_60313913/measurement_60313913_000000000004.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/measurement_60313913/measurement_60313913_000000000005.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/measurement_60313913/measurement_60313913_000000000006.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/measurement_60313913/measurement_60313913_000000000007.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/measurement_60313913/measurement_60313913_000000000008.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/measurement_60313913/measurement_60313913_000000000009.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/observation_04318565/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/observation_04318565/observation_04318565_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/observation_65805338/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/observation_65805338/observation_65805338_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/person_51780597/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/person_51780597/person_51780597_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/procedure_04318565/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/procedure_04318565/procedure_04318565_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/procedure_47173302/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/procedure_47173302/procedure_47173302_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/procedure_93801899/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250205/procedure_93801899/procedure_93801899_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/:

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/condition_57829836/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/condition_57829836/condition_57829836_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/condition_87448626/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/condition_87448626/condition_87448626_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/condition_97626158/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/condition_97626158/condition_97626158_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/measurement_05885865/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/measurement_05885865/measurement_05885865_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/observation_65805338/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/observation_65805338/observation_65805338_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/person_51780597/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/person_51780597/person_51780597_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/procedure_47173302/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/procedure_47173302/procedure_47173302_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/survey_16801330/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/survey_16801330/survey_16801330_000000000000.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/survey_16801330/survey_16801330_000000000001.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/survey_16801330/survey_16801330_000000000002.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/survey_16801330/survey_16801330_000000000003.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/survey_16801330/survey_16801330_000000000004.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/survey_16801330/survey_16801330_000000000005.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/survey_16801330/survey_16801330_000000000006.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/survey_16801330/survey_16801330_000000000007.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/survey_16801330/survey_16801330_000000000008.csv
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/survey_16801330/survey_16801330_000000000009.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/survey_28116944/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/survey_28116944/survey_28116944_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/survey_81293648/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250212/survey_81293648/survey_81293648_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250213/:

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250213/condition_32581449/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250213/condition_32581449/condition_32581449_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250213/condition_79586544/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250213/condition_79586544/condition_79586544_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250213/condition_84516414/:
gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250213/condition_84516414/condition_84516414_000000000000.csv

gs://fc-secure-784622b3-a3b0-42a1-a555-372ab8841bd6/bq_exports/micah_hysong@researchallofus.org/20250213/condition_93775608/: