In [1]:
lapply(c('viridis', 'ggthemes', 'skimr'),
       function(pkg_name) { if(! pkg_name %in% installed.packages()) { install.packages(pkg_name)} } )

library(viridis)    # A nice color scheme for plots.
library(ggthemes)   # Common themes to change the look and feel of plots.
library(scales)     # Graphical scales map data to aesthetics in plots.
library(skimr)      # Better summaries of data.
library(lubridate)  # Date library from the tidyverse.
library(tidyverse)  # Data wrangling packages.
library(bigrquery)  # Data extraction from Google BigQuery

## Plot setup.
theme_set(theme_bw(base_size = 14)) # Default theme for plots.

#' Returns a data frame with a y position and a label, for use annotating ggplot boxplots.
#'
#' @param d A data frame.
#' @return A data frame with column y as max and column label as length.
get_boxplot_fun_data <- function(df) {
  return(data.frame(y = max(df), label = stringr::str_c('N = ', length(df))))
}

system("jupyter nbconvert --to notebook --execute '/home/jupyter/workspace/rw-migration-aou-rw-67cadd48/Setting_Env_Variables.ipynb' --stdout")

[[1]]
NULL

[[2]]
NULL

[[3]]
NULL

Loading required package: viridisLite


Attaching package: ‘scales’


The following object is masked from ‘package:viridis’:

    viridis_pal



Attaching package: ‘lubridate’


The following objects are masked from ‘package:base’:

    date, intersect, setdiff, union


── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr   1.2.1     ✔ readr   2.2.0
✔ forcats 1.0.1     ✔ stringr 1.6.0
✔ ggplot2 4.0.2     ✔ tibble  3.3.1
✔ purrr   1.2.1     ✔ tidyr   1.3.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ readr::col_factor() masks scales::col_factor()
✖ purrr::discard()    masks scales::discard()
✖ dplyr::filter()     masks stats::filter()
✖ dplyr::lag()        masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

# Load and Merge Data

In [2]:
current_directory <- "/home/jupyter/workspace/rw-migration-aou-rw-67cadd48"
output_dir <- "/home/jupyter/workspace/rw-migration-aou-rw-67cadd48/data"

demo_file = paste0(current_directory, "/data/Demographic_and_ancestry_covariates.csv")
demo  <- read_csv(demo_file) |> 
    select(-c(income)) |> 
    rename(age = age_at_last_event)

ses_file = paste0(current_directory, "/data/SES_data.csv")
ses_data  <- read_csv(ses_file) |> 
    select(-c(education))

Rows: 135557 Columns: 51
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr   (9): SexGender, ancestry_pred, education, where_born, military, health...
dbl  (30): person_id, race_unknown, age_today, PC_1, PC_2, PC_3, PC_4, PC_5,...
lgl   (8): AIAN, Asian, Black, Mid, Multiple, PI, White, His
dttm  (1): basics_survey_datetime
date  (3): date_of_birth, min_date, max_date

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 214915 Columns: 13
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (13): person_id, income, education, per_poverty_threshold, individual_po...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [3]:
# Select the required columns from pov_data and merge with all_data
all_data <- merge(
  demo,
  ses_data,
  by = "person_id"
)

# Format Data

In [4]:
# Convert indicator columns into a single 'Race' column
all_data2 <- all_data %>%
  pivot_longer(
    cols = c(AIAN, Asian, Black, Mid, Multiple, PI, White, race_unknown),
    names_to = "racial_identity",
    values_to = "indicator"
  ) %>%
  filter(indicator == 1) %>%
  select(-indicator)

In [5]:
all_data2$education<-factor(all_data2$education,
                             levels = c("Less than high school degree or equivalent",
                                        "Twelve or GED",
                                         "College One to Three",
                                       "College graduate",
                                        "Advanced degree"),
                             ordered = TRUE)

all_data2$income_grouped<-factor(all_data2$income_grouped,
                             levels = c("<50k",
                                       "50k-100k",
                                       "100k-150k",
                                       ">150k"),
                             ordered = TRUE)


all_data2$racial_identity<-factor(all_data2$racial_identity,
                             levels = c("AIAN",
                                       "Asian",
                                       "Black",
                                       "Mid",
                                       "Multiple",
                                       "PI",
                                       "White",
                                       "race_unknown"),
                             ordered = TRUE)
# Rename some levels
levels(all_data2$racial_identity)[levels(all_data2$racial_identity) == "AIAN"] <- "American Indian or Alaska Native"
levels(all_data2$racial_identity)[levels(all_data2$racial_identity) == "Mid"] <- "Middle Eastern or North African"
levels(all_data2$racial_identity)[levels(all_data2$racial_identity) == "PI"] <- "Native Hawaiian or Other Pacific Islander"
levels(all_data2$racial_identity)[levels(all_data2$racial_identity) == "race_unknown"] <- "PNA or Skip"
names(all_data2)[names(all_data2) == "racial_identity"] <- "racial identity"



all_data2$disabled<-factor(all_data2$disabled,
                             levels = c("Yes",
                                       "No",
                                       "Missing"),
                             ordered = TRUE)
names(all_data2)[names(all_data2) == "disabled"] <- "disability"
levels(all_data2$disability)[levels(all_data2$disability) == "Missing"] <- "PNA or Skip"




names(all_data2)[names(all_data2) == "His"] <- "Hispanic"
all_data2$Hispanic<-factor(all_data2$Hispanic)
levels(all_data2$Hispanic)[levels(all_data2$Hispanic) == TRUE] <- "Yes"
levels(all_data2$Hispanic)[levels(all_data2$Hispanic) == FALSE] <- "No"
all_data2$Hispanic<-factor(all_data2$Hispanic,
                             levels = c("Yes",
                                       "No"),
                             ordered = TRUE)



all_data2$sexual_orientation<-factor(all_data2$sexual_orientation,
                             levels = c("Queer",
                                       "Straight",
                                       "PNA or Skip"),
                             ordered = TRUE)
names(all_data2)[names(all_data2) == "sexual_orientation"] <- "sexual orientation"


all_data2$SexGender<-factor(all_data2$SexGender)
levels(all_data2$SexGender)[levels(all_data2$SexGender) == "Cis_female"] <- "Cisgender Female"
levels(all_data2$SexGender)[levels(all_data2$SexGender) == "Cis_male"] <- "Cisgender Male"
levels(all_data2$SexGender)[levels(all_data2$SexGender) == "SGM"] <- "Sexual and Gender Minority (SGM)"
names(all_data2)[names(all_data2) == "SexGender"] <- "sex/gender"


names(all_data2)[names(all_data2) == "age_at_last_event"] <- "age"


all_data2$where_born<-factor(all_data2$where_born)
levels(all_data2$where_born)[levels(all_data2$where_born) == "USA"] <- "Yes"
levels(all_data2$where_born)[levels(all_data2$where_born) == "elsewhere"] <- "No"
all_data2$where_born<-factor(all_data2$where_born,
                             levels = c("Yes",
                                       "No",
                                       "Skip"),
                             ordered = TRUE)
names(all_data2)[names(all_data2) == "where_born"] <- "born in the USA?"

all_data2$military[is.na(all_data2$military)] <- "Skip or PNA"
all_data2$military<-factor(all_data2$military,
                             levels = c("Yes",
                                       "No",
                                       "Skip or PNA"),
                             ordered = TRUE)
names(all_data2)[names(all_data2) == "military"] <- "military active duty (past or present)"


all_data2$healthcare <- as.character(all_data2$healthcare)
all_data2$healthcare[all_data2$healthcare == "Skip"] <- "Skip or NA"
all_data2$healthcare[is.na(all_data2$healthcare)] <- "Skip or NA"


all_data2$healthcare<-factor(all_data2$healthcare,
                             levels = c("Employer Or Union",
                                       "Medicaid",
                                       "Medicare",
                                       "Other",
                                       "Purchased",
                                       "VA or Military",
                                        "None", 
                                       "Skip or NA"),
                             ordered = TRUE)
names(all_data2)[names(all_data2) == "healthcare"] <- "health insurance"

# Get full cohort summary

In [7]:
# Columns to summarize
cols <- c(
  "age", "sex/gender", "ancestry_pred", "racial identity", "Hispanic",
  "education", "income_grouped", 
    "per_poverty_threshold", "fraction_assisted_income", "fraction_no_high_school_education",
    "lower_median_income", "fraction_no_health_insurance", "fraction_poverty", 
    "fraction_vacant_housing", "deprivation_index", "racial identity",   
    "sexual orientation", "disability", "born in the USA?",
  "military active duty (past or present)", "health insurance"
)


selected_data <- all_data2 |> select(cols)

# Unified summarizer
summarize_column_detailed_cohorts <- function(df, cols) {
  summary_list <- list()
  message("Number of rows: ", nrow(df))

  for (col_name in cols) {
    column <- df[[col_name]]

    if (is.numeric(column)) {
      # Numeric summary → single row
      summary_list[[col_name]] <- data.frame(
        Variable = col_name,
        Value = NA,
        Summary = sprintf("%.2f (± %.2f)", 
                          mean(column, na.rm = TRUE), 
                          sd(column, na.rm = TRUE))
      )
    } else {
      # Categorical summary → multiple rows
      counts <- as.data.frame(table(column, useNA = "ifany"))
      counts$Percent <- round(100 * counts$Freq / sum(counts$Freq), 1)
      summary_list[[col_name]] <- data.frame(
        Variable = col_name,
        Value = as.character(counts$column),
        Summary = paste0(counts$Freq, " (", counts$Percent, "%)")
      )
    }
  }

  # Combine all results safely
  do.call(rbind, summary_list)
}


detailed_summary_table <- summarize_column_detailed_cohorts(selected_data, cols) 
rownames(detailed_summary_table) <- NULL


# Preview
head(detailed_summary_table, 60)


write_excel_csv(
  detailed_summary_table,
  file.path(output_dir, "Whole_sample_demographics.csv")
)

Number of rows: 104908

   Variable
1  age
2  sex/gender
3  sex/gender
4  sex/gender
5  ancestry_pred
6  ancestry_pred
7  ancestry_pred
8  ancestry_pred
9  ancestry_pred
10 ancestry_pred
11 racial identity
12 racial identity
13 racial identity
14 racial identity
15 racial identity
16 racial identity
17 racial identity
18 racial identity
19 Hispanic
20 Hispanic
21 education
22 education
23 education
24 education
25 education
26 income_grouped
27 income_grouped
28 income_grouped
29 income_grouped
30 per_poverty_threshold
31 fraction_assisted_income
32 fraction_no_high_school_education
33 lower_median_income
34 fraction_no_health_insurance
35 fraction_poverty
36 fraction_vacant_housing
37 deprivation_index
38 sexual orientation
39 sexual orientation
40 sexual orientation
41 disability
42 disability
43 disability
44 born in the USA?
45 born in the USA?
46 born in the USA?
47 military active duty (past or present)
48 military active duty (past or present)
49 military active duty (past or present)
50 health insurance
51 health insurance
52 health insurance
53 health insurance
54 health insurance
55 health insurance
56 health insurance
57 health insurance
   Value                                      Summary
1  NA                                         57.30 (± 16.49)
2  Cisgender Female                           63269 (60.3%)
3  Cisgender Male                             39226 (37.4%)
4  Sexual and Gender Minority (SGM)           2413 (2.3%)
5  afr                                        19368 (18.5%)
6  amr                                        10465 (10%)
7  eas                                        1375 (1.3%)
8  eur                                        72424 (69%)
9  mid                                        330 (0.3%)
10 sas                                        946 (0.9%)
11 American Indian or Alaska Native           0 (0%)
12 Asian                                      2004 (1.9%)
13 Black                                      17507 (16.7%)
14 Middle Eastern or North African            446 (0.4%)
15 Multiple                                   1641 (1.6%)
16 Native Hawaiian or Other Pacific Islander  48 (0%)
17 White                                      70539 (67.2%)
18 PNA or Skip                                12723 (12.1%)
19 Yes                                        11912 (11.4%)
20 No                                         92996 (88.6%)
21 Less than high school degree or equivalent 5662 (5.4%)
22 Twelve or GED                              16042 (15.3%)
23 College One to Three                       27013 (25.7%)
24 College graduate                           27318 (26%)
25 Advanced degree                            28873 (27.5%)
26 <50k                                       46702 (44.5%)
27 50k-100k                                   26907 (25.6%)
28 100k-150k                                  14937 (14.2%)
29 >150k                                      16362 (15.6%)
30 NA                                         401.96 (± 351.52)
31 NA                                         0.14 (± 0.06)
32 NA                                         0.10 (± 0.04)
33 NA                                         0.67 (± 0.09)
34 NA                                         0.02 (± 0.01)
35 NA                                         0.13 (± 0.05)
36 NA                                         0.10 (± 0.05)
37 NA                                         0.40 (± 0.12)
38 Queer                                      9400 (9%)
39 Straight                                   93822 (89.4%)
40 PNA or Skip                                1686 (1.6%)
41 Yes                                        19803 (18.9%)
42 No                                         50895 (48.5%)
43 PNA or Skip                                34210 (32.6%)
44 Yes                                        92736 (88.4%)
45 No                                         11517 (11%)
46 Skip                                       655 (0.6%)
47 Yes                                        13983 (13.3%)
48 No                                         90102 (85.9%)
49 Skip or PNA                                823 (0.8%)
50 Employer Or Union                          40462 (38.6%)
51 Medicaid                                   17339 (16.5%)
52 Medicare                                   15644 (14.9%)
53 Other                                      2637 (2.5%)
54 Purchased                                  8808 (8.4%)
55 VA or Military                             7978 (7.6%)
56 None                                       237 (0.2%)
57 Skip or NA                                 11803 (11.3%)

# Get cohort summary for smaller richer SDoH survey cohort

In [14]:
# Imputed individual-level SDoH data from Social Determinants of Health Measurement Models V8 community workspace
name_of_file_in_bucket <- 'imputed_individual_level_SDOH.csv'
system(paste0("gsutil cp gs://rw-migration-aou-rw-55feedb6/notebooks/imputed_individual_level_SDOH.csv ."), intern=T)

sdoh_var <-c('Own Home', 'Health Literacy', 'Housing Quality', 'Housing Instability',
             'Food Insecurity', 'Walkability', 'Loneliness', 'Crime', 'Physical Disorder', 'Social Disorder',
             'Everyday Discrimination', 'Medical Discrimination', 'Social Cohesion', 'Stress', 
             'Social Support', 'Spiritual Experiences', 'Health Coverage', 'Healthcare Utilization',
             'Delayed Care', 'Can\'t afford care', 'Worried Pay', 'Respect'
)

sdoh_data <- read_csv(name_of_file_in_bucket) |> select(c("person_id", sdoh_var))

sdoh_survey_data <- merge(
  all_data2,
  sdoh_data,
  by = "person_id"
)


selected_data <- sdoh_survey_data |> select(cols)

detailed_summary_table <- summarize_column_detailed_cohorts(selected_data, cols) 
rownames(detailed_summary_table) <- NULL

# Preview
head(detailed_summary_table, 60)

write_excel_csv(
  detailed_summary_table,
  file.path(output_dir, "Richer_sdoh_sample_demographics.csv")
)

character(0)

Rows: 54313 Columns: 37
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (1): SexGender
dbl (30): person_id, race_unknown, record_depth, visit_frequency, age, Educa...
lgl  (6): Black, Mid, Multiple, White, His, AANHPI

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Number of rows: 47455

   Variable
1  age
2  sex/gender
3  sex/gender
4  sex/gender
5  ancestry_pred
6  ancestry_pred
7  ancestry_pred
8  ancestry_pred
9  ancestry_pred
10 ancestry_pred
11 racial identity
12 racial identity
13 racial identity
14 racial identity
15 racial identity
16 racial identity
17 racial identity
18 racial identity
19 Hispanic
20 Hispanic
21 education
22 education
23 education
24 education
25 education
26 income_grouped
27 income_grouped
28 income_grouped
29 income_grouped
30 per_poverty_threshold
31 fraction_assisted_income
32 fraction_no_high_school_education
33 lower_median_income
34 fraction_no_health_insurance
35 fraction_poverty
36 fraction_vacant_housing
37 deprivation_index
38 sexual orientation
39 sexual orientation
40 sexual orientation
41 disability
42 disability
43 disability
44 born in the USA?
45 born in the USA?
46 born in the USA?
47 military active duty (past or present)
48 military active duty (past or present)
49 military active duty (past or present)
50 health insurance
51 health insurance
52 health insurance
53 health insurance
54 health insurance
55 health insurance
56 health insurance
57 health insurance
   Value                                      Summary
1  NA                                         59.51 (± 15.61)
2  Cisgender Female                           29094 (61.3%)
3  Cisgender Male                             17386 (36.6%)
4  Sexual and Gender Minority (SGM)           975 (2.1%)
5  afr                                        3967 (8.4%)
6  amr                                        2816 (5.9%)
7  eas                                        594 (1.3%)
8  eur                                        39572 (83.4%)
9  mid                                        129 (0.3%)
10 sas                                        377 (0.8%)
11 American Indian or Alaska Native           0 (0%)
12 Asian                                      814 (1.7%)
13 Black                                      3633 (7.7%)
14 Middle Eastern or North African            181 (0.4%)
15 Multiple                                   726 (1.5%)
16 Native Hawaiian or Other Pacific Islander  13 (0%)
17 White                                      38630 (81.4%)
18 PNA or Skip                                3458 (7.3%)
19 Yes                                        3119 (6.6%)
20 No                                         44336 (93.4%)
21 Less than high school degree or equivalent 730 (1.5%)
22 Twelve or GED                              3965 (8.4%)
23 College One to Three                       11172 (23.5%)
24 College graduate                           14468 (30.5%)
25 Advanced degree                            17120 (36.1%)
26 <50k                                       13839 (29.2%)
27 50k-100k                                   14726 (31%)
28 100k-150k                                  8915 (18.8%)
29 >150k                                      9975 (21%)
30 NA                                         503.43 (± 352.14)
31 NA                                         0.13 (± 0.05)
32 NA                                         0.09 (± 0.04)
33 NA                                         0.65 (± 0.10)
34 NA                                         0.02 (± 0.01)
35 NA                                         0.12 (± 0.04)
36 NA                                         0.09 (± 0.05)
37 NA                                         0.38 (± 0.11)
38 Queer                                      4471 (9.4%)
39 Straight                                   42496 (89.6%)
40 PNA or Skip                                488 (1%)
41 Yes                                        11141 (23.5%)
42 No                                         32842 (69.2%)
43 PNA or Skip                                3472 (7.3%)
44 Yes                                        43504 (91.7%)
45 No                                         3748 (7.9%)
46 Skip                                       203 (0.4%)
47 Yes                                        7428 (15.7%)
48 No                                         39770 (83.8%)
49 Skip or PNA                                257 (0.5%)
50 Employer Or Union                          21045 (44.3%)
51 Medicaid                                   3833 (8.1%)
52 Medicare                                   7577 (16%)
53 Other                                      798 (1.7%)
54 Purchased                                  4404 (9.3%)
55 VA or Military                             4551 (9.6%)
56 None                                       27 (0.1%)
57 Skip or NA                                 5220 (11%)

# Case Control Deomographics

In [15]:
name_of_file_in_bucket <- 'Case_Control_df.csv'
system(paste0("gsutil cp gs://rw-migration-aou-rw-55feedb6/notebooks/Case_Control_df.csv ."), intern=T)
case_control  <- read_csv(name_of_file_in_bucket)

character(0)

Rows: 265954 Columns: 10
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (10): person_id, Asthma, Afib, BreastC, CKD, CHD, HyperC, ProstateC, t2d...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [16]:
merged_df<-merge(all_data2, case_control)
colnames(merged_df)

 [1] "person_id"
 [2] "date_of_birth"
 [3] "Hispanic"
 [4] "sex/gender"
 [5] "age_today"
 [6] "ancestry_pred"
 [7] "PC_1"
 [8] "PC_2"
 [9] "PC_3"
[10] "PC_4"
[11] "PC_5"
[12] "PC_6"
[13] "PC_7"
[14] "PC_8"
[15] "PC_9"
[16] "PC_10"
[17] "PC_11"
[18] "PC_12"
[19] "PC_13"
[20] "PC_14"
[21] "PC_15"
[22] "PC_16"
[23] "number_living"
[24] "education"
[25] "born in the USA?"
[26] "military active duty (past or present)"
[27] "health insurance"
[28] "disability"
[29] "sexual orientation"
[30] "LGBTQIA"
[31] "basics_survey_datetime"
[32] "income_grouped"
[33] "min_date"
[34] "max_date"
[35] "ehr_length"
[36] "relative_health"
[37] "record_depth"
[38] "visit_frequency"
[39] "age"
[40] "record_depth_winsorized"
[41] "visit_frequency_winsorized"
[42] "age2"
[43] "income"
[44] "per_poverty_threshold"
[45] "individual_poverty"
[46] "american_community_survey_year"
[47] "fraction_assisted_income"
[48] "fraction_no_high_school_education"
[49] "lower_median_income"
[50] "fraction_no_health_insurance"
[51] "fraction_poverty"
[52] "fraction_vacant_housing"
[53] "deprivation_index"
[54] "racial identity"
[55] "Asthma"
[56] "Afib"
[57] "BreastC"
[58] "CKD"
[59] "CHD"
[60] "HyperC"
[61] "ProstateC"
[62] "t2d"
[63] "t1d"

In [17]:
diseases<-c("Asthma", "Afib", "BreastC", "CKD", "CHD", "HyperC", "ProstateC", "t2d", "t1d")

In [18]:
summarize_disease_cohort <- function(cohort, diseases, case_value = 1) {
  output_df <- data.frame()
  
  for (disease in diseases) {
    if (disease %in% colnames(cohort)) {
      df <- cohort[cohort[[disease]] == case_value & !is.na(cohort[[disease]]), ]
      n <- nrow(df)
        
      output_df[disease, "Disease"] <- disease
     
        
      #Case control
       if (case_value == 1) {
          output_df[disease, "Status"] <- "Case"   
       } else { output_df[disease, "Status"] <- "Control" }
    
      output_df[disease, "Sample size"] <- n
      
      if (n > 0) {
        # Median age (SD)
        output_df[disease, "Age (sd)"] <- paste0(
          round(median(df$age, na.rm = TRUE), 2), 
          " (", round(sd(df$age, na.rm = TRUE), 2), ")"
        )

        # Helper function for count + percent
        fmt <- function(x) {
          count <- sum(x, na.rm = TRUE)
          if (count > 0 & count < 20) return("<20")
          percent <- round(100 * count / n, 1)
          paste0(count, " (", percent, "%)")
        }

        # Sex/Gender
        output_df[disease, "Cisgender Male"] <- fmt(df$`sex/gender` == "Cisgender Male")
        output_df[disease, "Cisgender Female"] <- fmt(df$`sex/gender` == "Cisgender Female")
        output_df[disease, "SGM"] <- fmt(df$`sex/gender` == "Sexual and Gender Minority (SGM)")

        # Race
        races <- c("Asian", "Black", "Middle Eastern or North African", "Multiple", 
                   "Native Hawaiian or Other Pacific Islander", "White")
        for (race in races) {
          output_df[disease, race] <- fmt(df$`racial identity` == race)
        }

        # Ethnicity
        output_df[disease, "Hispanic"] <- fmt(df$Hispanic == "Yes")

        # Record depth (numeric only)
        output_df[disease, "Median Record Depth"] <- median(na.omit(df$record_depth))

        # Disability (if column exists)
        output_df[disease, "Disability"] <- if ("disability" %in% colnames(df)) fmt(df$disability == "Yes") else NA

        # LGBTQIA
        output_df[disease, "LGBTQIA"] <- fmt(df$LGBTQIA == 1)

        # Income
        output_df[disease, "Income <50k"] <- fmt(df$income_grouped == "<50k")
        output_df[disease, "Income >150k"] <- fmt(df$income_grouped == ">150k")

        # Education
        output_df[disease, "Advanced Degree"]            <- fmt(df$education == "Advanced degree")
        output_df[disease, "Less than HighSchool"] <- fmt(df$education == "Less than high school degree or equivalent")
      }
    }
  }
  
  return(output_df)
}

In [21]:
cases<-summarize_disease_cohort(merged_df, diseases, 1)
rownames(cases) <- NULL
controls<-summarize_disease_cohort(merged_df, diseases, 0)
rownames(controls) <- NULL


# Interleave rows
n <- nrow(cases)
interleaved <- bind_rows(
  cases %>% mutate(.order = (1:n) * 2 - 1),
  controls %>% mutate(.order = (1:n) * 2)
) %>%
  arrange(.order) %>%
  select(-.order)

# View result
interleaved <- interleaved %>%
  relocate(Status, .after = 2)

    
#Save
interleaved
write_excel_csv(
  interleaved,
  file.path(output_dir, "Case_control_demographics.csv")
)

   Disease   Status  Sample size Age (sd)   Cisgender Male Cisgender Female
1  Asthma    Case    12315       54 (16.06) 3088 (25.1%)   8927 (72.5%)
2  Asthma    Control 18005       54 (17.25) 7852 (43.6%)   9733 (54.1%)
3  Afib      Case     8222       72 (11.92) 4693 (57.1%)   3301 (40.1%)
4  Afib      Control 17685       63 (15.02) 6433 (36.4%)   10841 (61.3%)
5  BreastC   Case     5324       68 (11.53) 0 (0%)         5220 (98%)
6  BreastC   Control 59963       56 (16.32) 0 (0%)         57671 (96.2%)
7  CKD       Case     9258       72 (12.16) 4365 (47.1%)   4849 (52.4%)
8  CKD       Control 31058       48 (15.25) 10460 (33.7%)  20598 (66.3%)
9  CHD       Case    14863       71 (11.15) 8783 (59.1%)   5719 (38.5%)
10 CHD       Control 85107       56 (16.31) 28395 (33.4%)  54778 (64.4%)
11 HyperC    Case    26693       68 (12.02) 11555 (43.3%)  14591 (54.7%)
12 HyperC    Control 11006       46 (15.15) 3386 (30.8%)   7358 (66.9%)
13 ProstateC Case     3586       74 (8.18)  3494 (97.4%)   <20
14 ProstateC Control  6226       72 (11.14) 6049 (97.2%)   0 (0%)
15 t2d       Case    17747       65 (12.58) 7912 (44.6%)   9411 (53%)
16 t2d       Control 35450       55 (16.73) 12115 (34.2%)  22562 (63.6%)
17 t1d       Case     1098       58 (15.99) 496 (45.2%)    583 (53.1%)
18 t1d       Control 35450       55 (16.73) 12115 (34.2%)  22562 (63.6%)
   SGM         Asian       Black         Middle Eastern or North African ⋯
1  300 (2.4%)  162 (1.3%)  2312 (18.8%)  33 (0.3%)                       ⋯
2  420 (2.3%)  566 (3.1%)  3516 (19.5%)  103 (0.6%)                      ⋯
3  228 (2.8%)  61 (0.7%)   811 (9.9%)    24 (0.3%)                       ⋯
4  411 (2.3%)  237 (1.3%)  3554 (20.1%)  52 (0.3%)                       ⋯
5  104 (2%)    80 (1.5%)   631 (11.9%)   <20                             ⋯
6  2292 (3.8%) 1115 (1.9%) 11102 (18.5%) 217 (0.4%)                      ⋯
7  44 (0.5%)   77 (0.8%)   2203 (23.8%)  26 (0.3%)                       ⋯
8  0 (0%)      944 (3%)    4071 (13.1%)  187 (0.6%)                      ⋯
9  361 (2.4%)  157 (1.1%)  2266 (15.2%)  47 (0.3%)                       ⋯
10 1934 (2.3%) 1790 (2.1%) 14229 (16.7%) 382 (0.4%)                      ⋯
11 547 (2%)    367 (1.4%)  3785 (14.2%)  102 (0.4%)                      ⋯
12 262 (2.4%)  374 (3.4%)  1777 (16.1%)  76 (0.7%)                       ⋯
13 91 (2.5%)   23 (0.6%)   417 (11.6%)   21 (0.6%)                       ⋯
14 177 (2.8%)  60 (1%)     554 (8.9%)    <20                             ⋯
15 424 (2.4%)  281 (1.6%)  4307 (24.3%)  66 (0.4%)                       ⋯
16 773 (2.2%)  675 (1.9%)  3795 (10.7%)  176 (0.5%)                      ⋯
17 <20         <20         199 (18.1%)   <20                             ⋯
18 773 (2.2%)  675 (1.9%)  3795 (10.7%)  176 (0.5%)                      ⋯
   Native Hawaiian or Other Pacific Islander White         Hispanic
1  <20                                       7823 (63.5%)  1688 (13.7%)
2  <20                                       10886 (60.5%) 2625 (14.6%)
3  <20                                       6644 (80.8%)  429 (5.2%)
4  <20                                       11145 (63%)   2237 (12.6%)
5  0 (0%)                                    4008 (75.3%)  443 (8.3%)
6  22 (0%)                                   38401 (64%)   7743 (12.9%)
7  <20                                       5888 (63.6%)  771 (8.3%)
8  <20                                       20548 (66.2%) 4817 (15.5%)
9  <20                                       10629 (71.5%) 1258 (8.5%)
10 34 (0%)                                   56744 (66.7%) 10136 (11.9%)
11 <20                                       19197 (71.9%) 2440 (9.1%)
12 <20                                       7330 (66.6%)  1209 (11%)
13 0 (0%)                                    2830 (78.9%)  176 (4.9%)
14 <20                                       4967 (79.8%)  402 (6.5%)
15 <20                                       10162 (57.3%) 2409 (13.6%)
16 <20                                       26505 (74.8%) 3586 (10.1%)
17 <20                                       739 (67.3%)   124 (11.3%)
18 <20                                       26505 (74.8%) 3586 (10.1%)
   Median Record Depth Disability    LGBTQIA      Income <50k   Income >150k
1  143                 2607 (21.2%)  1628 (13.2%) 5935 (48.2%)  1712 (13.9%)
2   34                 2333 (13%)    1935 (10.7%) 7941 (44.1%)  2968 (16.5%)
3  189                 2286 (27.8%)  677 (8.2%)   3410 (41.5%)  1189 (14.5%)
4  183                 3749 (21.2%)  1735 (9.8%)  8601 (48.6%)  2342 (13.2%)
5  172                 988 (18.6%)   337 (6.3%)   1944 (36.5%)  996 (18.7%)
6   95                 10553 (17.6%) 7113 (11.9%) 28821 (48.1%) 8124 (13.5%)
7  201                 2583 (27.9%)  567 (6.1%)   5081 (54.9%)  815 (8.8%)
8   83                 4775 (15.4%)  3165 (10.2%) 13277 (42.7%) 5353 (17.2%)
9  200                 4106 (27.6%)  1256 (8.5%)  7260 (48.8%)  1861 (12.5%)
10  85                 14528 (17.1%) 9253 (10.9%) 36899 (43.4%) 13844 (16.3%)
11 181                 5653 (21.2%)  2170 (8.1%)  11240 (42.1%) 4167 (15.6%)
12  87                 1457 (13.2%)  1429 (13%)   4297 (39%)    2170 (19.7%)
13 180                 816 (22.8%)   282 (7.9%)   1039 (29%)    788 (22%)
14 234                 2515 (40.4%)  506 (8.1%)   2433 (39.1%)  669 (10.7%)
15 163                 5125 (28.9%)  1702 (9.6%)  10075 (56.8%) 1377 (7.8%)
16  96                 5359 (15.1%)  3884 (11%)   12969 (36.6%) 6979 (19.7%)
17 149                 303 (27.6%)   119 (10.8%)  534 (48.6%)   131 (11.9%)
18  96                 5359 (15.1%)  3884 (11%)   12969 (36.6%) 6979 (19.7%)
   Advanced Degree Less than HighSchool
1  3098 (25.2%)    692 (5.6%)
2  5178 (28.8%)    1179 (6.5%)
3  2500 (30.4%)    309 (3.8%)
4  4460 (25.2%)    1276 (7.2%)
5  1766 (33.2%)    167 (3.1%)
6  15427 (25.7%)   3454 (5.8%)
7  2091 (22.6%)    566 (6.1%)
8  8507 (27.4%)    1649 (5.3%)
9  3738 (25.1%)    950 (6.4%)
10 23876 (28.1%)   4376 (5.1%)
11 7880 (29.5%)    1292 (4.8%)
12 3548 (32.2%)    407 (3.7%)
13 1393 (38.8%)    99 (2.8%)
14 1550 (24.9%)    86 (1.4%)
15 3286 (18.5%)    1420 (8%)
16 11635 (32.8%)   1165 (3.3%)
17 233 (21.2%)     43 (3.9%)
18 11635 (32.8%)   1165 (3.3%)

# Case Control Demographics Richer SDoH cohort

In [20]:
sdoh_survey_data_case_control<-merge(sdoh_survey_data, case_control)
diseases_short<-c("Asthma", "Afib",  "CKD", "CHD", "HyperC", "t2d")

In [22]:
cases<-summarize_disease_cohort(sdoh_survey_data_case_control, diseases, 1)
rownames(cases) <- NULL
controls<-summarize_disease_cohort(sdoh_survey_data_case_control, diseases, 0)
rownames(controls) <- NULL


# Interleave rows
n <- nrow(cases)
interleaved <- bind_rows(
  cases %>% mutate(.order = (1:n) * 2 - 1),
  controls %>% mutate(.order = (1:n) * 2)
) %>%
  arrange(.order) %>%
  select(-.order)

# View result
interleaved <- interleaved %>%
  relocate(Status, .after = 2)

    
#Save
interleaved
write_excel_csv(
  interleaved,
  file.path(output_dir, "Case_control_demographics_richer_sdoh.csv")
)

   Disease   Status  Sample size Age (sd)   Cisgender Male Cisgender Female
1  Asthma    Case     5557       58 (15.44) 1384 (24.9%)   4043 (72.8%)
2  Asthma    Control  7735       59 (16.65) 3329 (43%)     4251 (55%)
3  Afib      Case     4043       72 (11.22) 2283 (56.5%)   1661 (41.1%)
4  Afib      Control  7623       66 (14.05) 2706 (35.5%)   4763 (62.5%)
5  BreastC   Case     2806       68 (10.75) 0 (0%)         2759 (98.3%)
6  BreastC   Control 27215       58 (15.7)  0 (0%)         26296 (96.6%)
7  CKD       Case     3799       72 (10.53) 1829 (48.1%)   1962 (51.6%)
8  CKD       Control 13810       52 (15.12) 4565 (33.1%)   9245 (66.9%)
9  CHD       Case     6274       72 (9.63)  3831 (61.1%)   2317 (36.9%)
10 CHD       Control 39229       60 (15.64) 12707 (32.4%)  25709 (65.5%)
11 HyperC    Case    12883       69 (11.2)  5624 (43.7%)   7054 (54.8%)
12 HyperC    Control  4970       48 (15.22) 1340 (27%)     3503 (70.5%)
13 ProstateC Case     1913       74 (7.52)  1876 (98.1%)   0 (0%)
14 ProstateC Control  3655       71 (10.84) 3564 (97.5%)   0 (0%)
15 t2d       Case     7578       67 (11.76) 3558 (47%)     3867 (51%)
16 t2d       Control 17511       59 (16.01) 5807 (33.2%)   11339 (64.8%)
17 t1d       Case      624       61 (15.13) 285 (45.7%)    330 (52.9%)
18 t1d       Control 17511       59 (16.01) 5807 (33.2%)   11339 (64.8%)
   SGM        Asian      Black        Middle Eastern or North African ⋯
1  130 (2.3%) 70 (1.3%)  532 (9.6%)   <20                             ⋯
2  155 (2%)   212 (2.7%) 592 (7.7%)   31 (0.4%)                       ⋯
3  99 (2.4%)  27 (0.7%)  209 (5.2%)   <20                             ⋯
4  154 (2%)   105 (1.4%) 675 (8.9%)   <20                             ⋯
5  47 (1.7%)  34 (1.2%)  198 (7.1%)   <20                             ⋯
6  919 (3.4%) 470 (1.7%) 2528 (9.3%)  101 (0.4%)                      ⋯
7  <20        33 (0.9%)  541 (14.2%)  <20                             ⋯
8  0 (0%)     366 (2.7%) 800 (5.8%)   78 (0.6%)                       ⋯
9  126 (2%)   46 (0.7%)  408 (6.5%)   <20                             ⋯
10 813 (2.1%) 745 (1.9%) 3058 (7.8%)  159 (0.4%)                      ⋯
11 205 (1.6%) 145 (1.1%) 941 (7.3%)   45 (0.3%)                       ⋯
12 127 (2.6%) 143 (2.9%) 386 (7.8%)   20 (0.4%)                       ⋯
13 37 (1.9%)  <20        124 (6.5%)   <20                             ⋯
14 91 (2.5%)  35 (1%)    167 (4.6%)   <20                             ⋯
15 153 (2%)   114 (1.5%) 1088 (14.4%) 27 (0.4%)                       ⋯
16 365 (2.1%) 276 (1.6%) 799 (4.6%)   67 (0.4%)                       ⋯
17 <20        <20        83 (13.3%)   <20                             ⋯
18 365 (2.1%) 276 (1.6%) 799 (4.6%)   67 (0.4%)                       ⋯
   Native Hawaiian or Other Pacific Islander White         Hispanic
1  <20                                       4369 (78.6%)  432 (7.8%)
2  <20                                       6100 (78.9%)  692 (8.9%)
3  <20                                       3577 (88.5%)  109 (2.7%)
4  0 (0%)                                    6202 (81.4%)  426 (5.6%)
5  0 (0%)                                    2357 (84%)    129 (4.6%)
6  <20                                       21498 (79%)   2012 (7.4%)
7  <20                                       2945 (77.5%)  150 (3.9%)
8  <20                                       11032 (79.9%) 1323 (9.6%)
9  <20                                       5344 (85.2%)  253 (4%)
10 <20                                       31690 (80.8%) 2762 (7%)
11 <20                                       10773 (83.6%) 594 (4.6%)
12 0 (0%)                                    3984 (80.2%)  331 (6.7%)
13 0 (0%)                                    1654 (86.5%)  56 (2.9%)
14 <20                                       3139 (85.9%)  201 (5.5%)
15 <20                                       5433 (71.7%)  699 (9.2%)
16 0 (0%)                                    15010 (85.7%) 1016 (5.8%)
17 0 (0%)                                    466 (74.7%)   56 (9%)
18 0 (0%)                                    15010 (85.7%) 1016 (5.8%)
   Median Record Depth Disability   LGBTQIA      Income <50k   Income >150k
1  158.0               1551 (27.9%) 724 (13%)    1836 (33%)    1061 (19.1%)
2   39.0               1257 (16.3%) 835 (10.8%)  1948 (25.2%)  1849 (23.9%)
3  176.0               1319 (32.6%) 326 (8.1%)   1209 (29.9%)  720 (17.8%)
4  203.0               2050 (26.9%) 748 (9.8%)   2276 (29.9%)  1438 (18.9%)
5  169.0               586 (20.9%)  176 (6.3%)   783 (27.9%)   609 (21.7%)
6  101.0               6060 (22.3%) 3208 (11.8%) 8887 (32.7%)  5132 (18.9%)
7  210.0               1394 (36.7%) 218 (5.7%)   1520 (40%)    465 (12.2%)
8   94.0               2741 (19.8%) 1495 (10.8%) 3843 (27.8%)  3202 (23.2%)
9  200.0               2165 (34.5%) 508 (8.1%)   2055 (32.8%)  1079 (17.2%)
10  95.0               8353 (21.3%) 4299 (11%)   11130 (28.4%) 8516 (21.7%)
11 177.0               3207 (24.9%) 1048 (8.1%)  3788 (29.4%)  2554 (19.8%)
12  93.0               829 (16.7%)  659 (13.3%)  1178 (23.7%)  1291 (26%)
13 171.0               495 (25.9%)  148 (7.7%)   365 (19.1%)   478 (25%)
14 207.0               1542 (42.2%) 302 (8.3%)   1154 (31.6%)  471 (12.9%)
15 178.0               2843 (37.5%) 745 (9.8%)   3229 (42.6%)  814 (10.7%)
16 103.0               3293 (18.8%) 1985 (11.3%) 4237 (24.2%)  4324 (24.7%)
17 169.5               211 (33.8%)  68 (10.9%)   255 (40.9%)   83 (13.3%)
18 103.0               3293 (18.8%) 1985 (11.3%) 4237 (24.2%)  4324 (24.7%)
   Advanced Degree Less than HighSchool
1  1884 (33.9%)    76 (1.4%)
2  3074 (39.7%)    156 (2%)
3  1501 (37.1%)    39 (1%)
4  2712 (35.6%)    111 (1.5%)
5  1107 (39.5%)    29 (1%)
6  9254 (34%)      498 (1.8%)
7  1174 (30.9%)    78 (2.1%)
8  4891 (35.4%)    256 (1.9%)
9  2144 (34.2%)    95 (1.5%)
10 14271 (36.4%)   601 (1.5%)
11 4770 (37%)      166 (1.3%)
12 2027 (40.8%)    30 (0.6%)
13 845 (44.2%)     <20
14 1064 (29.1%)    27 (0.7%)
15 1890 (24.9%)    258 (3.4%)
16 6959 (39.7%)    137 (0.8%)
17 153 (24.5%)     <20
18 6959 (39.7%)    137 (0.8%)

# SDoH Quintile Deomographics

In [23]:
sdoh_var <- c(
  "per_poverty_threshold", "education",
  "fraction_assisted_income", "fraction_no_high_school_education",
  "lower_median_income", "fraction_no_health_insurance",
  "fraction_poverty", "fraction_vacant_housing",
  "deprivation_index"
)

merged_df <- merged_df %>%
  mutate(across(all_of(sdoh_var), ~ as.numeric(as.character(.))))

#Compute Q1 and Q5
quantiles <- merged_df %>%
  pivot_longer(
    cols = all_of(sdoh_var),
    names_to = "domain",
    values_to = "value"
  ) %>%
  group_by(domain) %>%
  summarize(
    q1 = quantile(value, 0.2, na.rm = TRUE),
    q5 = quantile(value, 0.8, na.rm = TRUE),
    .groups = "drop"
  )

#Add Q1 / Q5 indicator columns back to original data
for (v in sdoh_var) {
  q1_val <- quantiles$q1[quantiles$domain == v]
  q5_val <- quantiles$q5[quantiles$domain == v]

  merged_df[[paste0(v, "_Q1")]] <- merged_df[[v]] <= q1_val
  merged_df[[paste0(v, "_Q5")]] <- merged_df[[v]] >= q5_val
}

Warning message:
“There was 1 warning in `mutate()`.
ℹ In argument: `across(all_of(sdoh_var), ~as.numeric(as.character(.)))`.
Caused by warning:
! NAs introduced by coercion”

In [24]:
summarize_disease_sdoh_quintiles <- function(
  cohort,
  diseases,
  sdoh_vars,
  quintiles = c("Q1", "Q5")
) {

  output_df <- data.frame(stringsAsFactors = FALSE)

  for (sdoh in sdoh_vars) {
    for (q in quintiles) {

      # works even if sdoh has spaces/symbols
      q_col <- paste0(sdoh, "_", q)

      if (!(q_col %in% names(cohort))) next

      stratum_df <- cohort[
        !is.na(cohort[[q_col]]) & cohort[[q_col]] == TRUE,
      , drop = FALSE]

      for (disease in diseases) {

        if (!(disease %in% names(cohort))) next

        df <- stratum_df[
          !is.na(stratum_df[[disease]]) & stratum_df[[disease]] == 1,
        , drop = FALSE]

        n <- nrow(df)

        row_id <- paste(sdoh, q, disease, sep = "_")

        output_df[row_id, "SDoH"]        <- sdoh
        output_df[row_id, "Stratum"]     <- q
        output_df[row_id, "Disease"]     <- disease
        output_df[row_id, "Sample size"] <- n

        if (n == 0) next

        # ---------------- helper ----------------
        fmt <- function(x) {
          count <- sum(x, na.rm = TRUE)
          if (count > 0 && count < 20) return("<20")
          pct <- round(100 * count / n, 1)
          paste0(count, " (", pct, "%)")
        }

        # ---------------- age ----------------
        output_df[row_id, "Age (median, sd)"] <- paste0(
          round(median(df$age, na.rm = TRUE), 2),
          " (", round(sd(df$age, na.rm = TRUE), 2), ")"
        )

        # ---------------- sex/gender ----------------
        output_df[row_id, "Cisgender Male"]   <- fmt(df[["sex/gender"]] == "Cisgender Male")
        output_df[row_id, "Cisgender Female"] <- fmt(df[["sex/gender"]] == "Cisgender Female")
        output_df[row_id, "SGM"]              <- fmt(df[["sex/gender"]] == "Sexual and Gender Minority (SGM)")

        # ---------------- race ----------------
        races <- c(
          "Asian",
          "Black",
          "Middle Eastern or North African",
          "Multiple",
          "Native Hawaiian or Other Pacific Islander",
          "White"
        )

        for (race in races) {
          output_df[row_id, race] <- fmt(df[["racial identity"]] == race)
        }

        # ---------------- ethnicity ----------------
        output_df[row_id, "Hispanic"] <- fmt(df$Hispanic == "Yes")

        # ---------------- record depth ----------------
        output_df[row_id, "Median Record Depth"] <-
          round(median(df$record_depth, na.rm = TRUE), 2)

        # ---------------- disability ----------------
        output_df[row_id, "Disability"] <-
          if ("disability" %in% names(df)) fmt(df$disability == "Yes") else NA

        # ---------------- LGBTQIA ----------------
        output_df[row_id, "LGBTQIA"] <-
          if ("LGBTQIA" %in% names(df)) fmt(df$LGBTQIA == 1) else NA

        # ---------------- income ----------------
        output_df[row_id, "Income <50k"]  <- fmt(df$income_grouped == "<50k")
        output_df[row_id, "Income >150k"] <- fmt(df$income_grouped == ">150k")

        # ---------------- education ----------------
        output_df[row_id, "Advanced Degree"] <-
          fmt(df$education == 1)

        output_df[row_id, "Less than HighSchool"] <-
          fmt(df$education == 5)
      }
    }
  }

  rownames(output_df) <- NULL
  output_df
}

table1 <- summarize_disease_sdoh_quintiles(
  cohort   = merged_df,
  diseases = diseases,
  sdoh_vars = sdoh_var
)

table1 
    
#Save
write_excel_csv(
  table1,
  file.path(output_dir, "Case_SDoH_quintiles_demographics.csv")
)

    SDoH                    Stratum Disease   Sample size Age (median, sd)
1   per_poverty_threshold   Q1      Asthma    3083        46 (14.61)
2   per_poverty_threshold   Q1      Afib      1163        65 (13.22)
3   per_poverty_threshold   Q1      BreastC    665        64 (11.85)
4   per_poverty_threshold   Q1      CKD       2080        64 (12.77)
5   per_poverty_threshold   Q1      CHD       3083        63 (11.85)
6   per_poverty_threshold   Q1      HyperC    4389        62 (12.3)
7   per_poverty_threshold   Q1      ProstateC  290        70 (8.95)
8   per_poverty_threshold   Q1      t2d       4834        60 (12.22)
9   per_poverty_threshold   Q1      t1d        267        51 (15.01)
10  per_poverty_threshold   Q5      Asthma    2228        62 (14.12)
11  per_poverty_threshold   Q5      Afib      1850        74 (10.76)
12  per_poverty_threshold   Q5      BreastC   1400        67 (10.6)
13  per_poverty_threshold   Q5      CKD       1380        74 (10.36)
14  per_poverty_threshold   Q5      CHD       2883        73 (9.53)
15  per_poverty_threshold   Q5      HyperC    6113        69 (10.86)
16  per_poverty_threshold   Q5      ProstateC 1144        74 (8.23)
17  per_poverty_threshold   Q5      t2d       2129        69 (10.73)
18  per_poverty_threshold   Q5      t1d        165        61 (14.8)
19  education               Q1      Asthma       0        NA
20  education               Q1      Afib         0        NA
21  education               Q1      BreastC      0        NA
22  education               Q1      CKD          0        NA
23  education               Q1      CHD          0        NA
24  education               Q1      HyperC       0        NA
25  education               Q1      ProstateC    0        NA
26  education               Q1      t2d          0        NA
27  education               Q1      t1d          0        NA
28  education               Q5      Asthma       0        NA
29  education               Q5      Afib         0        NA
30  education               Q5      BreastC      0        NA
⋮   ⋮                       ⋮       ⋮         ⋮           ⋮
133 fraction_vacant_housing Q1      ProstateC  907        75 (7.98)
134 fraction_vacant_housing Q1      t2d       2910        67 (12.47)
135 fraction_vacant_housing Q1      t1d        205        60 (16.65)
136 fraction_vacant_housing Q5      Asthma    2390        53 (15.47)
137 fraction_vacant_housing Q5      Afib      1405        70 (12.62)
138 fraction_vacant_housing Q5      BreastC   1051        67 (11.27)
139 fraction_vacant_housing Q5      CKD       1989        69 (12.15)
140 fraction_vacant_housing Q5      CHD       3078        68 (12.22)
141 fraction_vacant_housing Q5      HyperC    4788        66 (11.97)
142 fraction_vacant_housing Q5      ProstateC  625        73 (8.22)
143 fraction_vacant_housing Q5      t2d       3856        63 (12.68)
144 fraction_vacant_housing Q5      t1d        238        56 (14.94)
145 deprivation_index       Q1      Asthma    2419        59 (15.85)
146 deprivation_index       Q1      Afib      2156        74 (11.08)
147 deprivation_index       Q1      BreastC   1236        67 (11.13)
148 deprivation_index       Q1      CKD       1898        75 (10.95)
149 deprivation_index       Q1      CHD       3309        74 (9.86)
150 deprivation_index       Q1      HyperC    5760        70 (11.39)
151 deprivation_index       Q1      ProstateC 1093        75 (7.87)
152 deprivation_index       Q1      t2d       3226        69 (12.06)
153 deprivation_index       Q1      t1d        223        62 (15.61)
154 deprivation_index       Q5      Asthma    2387        51 (15.12)
155 deprivation_index       Q5      Afib      1233        70 (12.3)
156 deprivation_index       Q5      BreastC    924        66 (12.04)
157 deprivation_index       Q5      CKD       1896        67 (12.7)
158 deprivation_index       Q5      CHD       2732        68 (11.63)
159 deprivation_index       Q5      HyperC    4655        66 (12.2)
160 deprivation_index       Q5      ProstateC  585        73 (8.6)
161 deprivation_index       Q5      t2d       3968        62 (12.47)
162 deprivation_index       Q5      t1d        247        54 (15.51)
    Cisgender Male Cisgender Female SGM        Asian      Black        ⋯
1   597 (19.4%)    2372 (76.9%)     114 (3.7%) <20        1250 (40.5%) ⋯
2   522 (44.9%)    583 (50.1%)      58 (5%)    <20        353 (30.4%)  ⋯
3   0 (0%)         646 (97.1%)      <20        <20        208 (31.3%)  ⋯
4   758 (36.4%)    1300 (62.5%)     22 (1.1%)  <20        995 (47.8%)  ⋯
5   1407 (45.6%)   1590 (51.6%)     86 (2.8%)  <20        1162 (37.7%) ⋯
6   1436 (32.7%)   2826 (64.4%)     127 (2.9%) 39 (0.9%)  1495 (34.1%) ⋯
7   274 (94.5%)    0 (0%)           <20        <20        114 (39.3%)  ⋯
8   1590 (32.9%)   3105 (64.2%)     139 (2.9%) 33 (0.7%)  2028 (42%)   ⋯
9   95 (35.6%)     164 (61.4%)      <20        <20        91 (34.1%)   ⋯
10  780 (35%)      1417 (63.6%)     31 (1.4%)  44 (2%)    73 (3.3%)    ⋯
11  1219 (65.9%)   595 (32.2%)      36 (1.9%)  <20        34 (1.8%)    ⋯
12  0 (0%)         1378 (98.4%)     22 (1.6%)  30 (2.1%)  37 (2.6%)    ⋯
13  816 (59.1%)    563 (40.8%)      <20        <20        106 (7.7%)   ⋯
14  2029 (70.4%)   805 (27.9%)      49 (1.7%)  48 (1.7%)  68 (2.4%)    ⋯
15  3195 (52.3%)   2833 (46.3%)     85 (1.4%)  125 (2%)   214 (3.5%)   ⋯
16  1119 (97.8%)   0 (0%)           25 (2.2%)  <20        52 (4.5%)    ⋯
17  1268 (59.6%)   823 (38.7%)      38 (1.8%)  91 (4.3%)  135 (6.3%)   ⋯
18  88 (53.3%)     75 (45.5%)       <20        <20        <20          ⋯
19  NA             NA               NA         NA         NA           ⋯
20  NA             NA               NA         NA         NA           ⋯
21  NA             NA               NA         NA         NA           ⋯
22  NA             NA               NA         NA         NA           ⋯
23  NA             NA               NA         NA         NA           ⋯
24  NA             NA               NA         NA         NA           ⋯
25  NA             NA               NA         NA         NA           ⋯
26  NA             NA               NA         NA         NA           ⋯
27  NA             NA               NA         NA         NA           ⋯
28  NA             NA               NA         NA         NA           ⋯
29  NA             NA               NA         NA         NA           ⋯
30  NA             NA               NA         NA         NA           ⋯
⋮   ⋮              ⋮                ⋮          ⋮          ⋮            ⋱
133 884 (97.5%)    0 (0%)           23 (2.5%)  <20        48 (5.3%)    ⋯
134 1524 (52.4%)   1306 (44.9%)     80 (2.7%)  88 (3%)    293 (10.1%)  ⋯
135 103 (50.2%)    98 (47.8%)       <20        <20        <20          ⋯
136 518 (21.7%)    1830 (76.6%)     42 (1.8%)  <20        824 (34.5%)  ⋯
137 699 (49.8%)    662 (47.1%)      44 (3.1%)  <20        274 (19.5%)  ⋯
138 0 (0%)         1028 (97.8%)     23 (2.2%)  <20        208 (19.8%)  ⋯
139 786 (39.5%)    1194 (60%)       <20        <20        797 (40.1%)  ⋯
140 1598 (51.9%)   1401 (45.5%)     79 (2.6%)  <20        883 (28.7%)  ⋯
141 1863 (38.9%)   2824 (59%)       101 (2.1%) 58 (1.2%)  1251 (26.1%) ⋯
142 607 (97.1%)    0 (0%)           <20        <20        128 (20.5%)  ⋯
143 1456 (37.8%)   2322 (60.2%)     78 (2%)    35 (0.9%)  1573 (40.8%) ⋯
144 101 (42.4%)    133 (55.9%)      <20        0 (0%)     80 (33.6%)   ⋯
145 697 (28.8%)    1657 (68.5%)     65 (2.7%)  51 (2.1%)  86 (3.6%)    ⋯
146 1391 (64.5%)   707 (32.8%)      58 (2.7%)  25 (1.2%)  47 (2.2%)    ⋯
147 0 (0%)         1210 (97.9%)     26 (2.1%)  <20        34 (2.8%)    ⋯
148 1105 (58.2%)   789 (41.6%)      <20        30 (1.6%)  109 (5.7%)   ⋯
149 2310 (69.8%)   932 (28.2%)      67 (2%)    52 (1.6%)  92 (2.8%)    ⋯
150 2942 (51.1%)   2707 (47%)       111 (1.9%) 107 (1.9%) 197 (3.4%)   ⋯
151 1068 (97.7%)   0 (0%)           25 (2.3%)  <20        32 (2.9%)    ⋯
152 1827 (56.6%)   1325 (41.1%)     74 (2.3%)  95 (2.9%)  201 (6.2%)   ⋯
153 123 (55.2%)    100 (44.8%)      0 (0%)     <20        <20          ⋯
154 563 (23.6%)    1773 (74.3%)     51 (2.1%)  27 (1.1%)  846 (35.4%)  ⋯
155 658 (53.4%)    544 (44.1%)      31 (2.5%)  <20        299 (24.2%)  ⋯
156 0 (0%)         910 (98.5%)      <20        23 (2.5%)  235 (25.4%)  ⋯
157 858 (45.3%)    1021 (53.9%)     <20        21 (1.1%)  807 (42.6%)  ⋯
158 1513 (55.4%)   1146 (41.9%)     73 (2.7%)  35 (1.3%)  799 (29.2%)  ⋯
159 1864 (40%)     2693 (57.9%)     98 (2.1%)  71 (1.5%)  1335 (28.7%) ⋯
160 567 (96.9%)    <20              <20        <20        143 (24.4%)  ⋯
161 1590 (40.1%)   2283 (57.5%)     95 (2.4%)  43 (1.1%)  1674 (42.2%) ⋯
162 110 (44.5%)    130 (52.6%)      <20        <20        92 (37.2%)   ⋯
    Native Hawaiian or Other Pacific Islander White        Hispanic
1   <20                                       966 (31.3%)  751 (24.4%)
2   0 (0%)                                    546 (46.9%)  220 (18.9%)
3   0 (0%)                                    221 (33.2%)  207 (31.1%)
4   <20                                       578 (27.8%)  436 (21%)
5   <20                                       1126 (36.5%) 687 (22.3%)
6   <20                                       1518 (34.6%) 1178 (26.8%)
7   0 (0%)                                    108 (37.2%)  52 (17.9%)
8   <20                                       1375 (28.4%) 1258 (26%)
9   <20                                       112 (41.9%)  57 (21.3%)
10  0 (0%)                                    1946 (87.3%) 110 (4.9%)
11  0 (0%)                                    1697 (91.7%) 37 (2%)
12  0 (0%)                                    1251 (89.4%) 43 (3.1%)
13  0 (0%)                                    1183 (85.7%) 25 (1.8%)
14  <20                                       2582 (89.6%) 71 (2.5%)
15  <20                                       5391 (88.2%) 188 (3.1%)
16  0 (0%)                                    1012 (88.5%) 26 (2.3%)
17  <20                                       1736 (81.5%) 89 (4.2%)
18  0 (0%)                                    142 (86.1%)  <20
19  NA                                        NA           NA
20  NA                                        NA           NA
21  NA                                        NA           NA
22  NA                                        NA           NA
23  NA                                        NA           NA
24  NA                                        NA           NA
25  NA                                        NA           NA
26  NA                                        NA           NA
27  NA                                        NA           NA
28  NA                                        NA           NA
29  NA                                        NA           NA
30  NA                                        NA           NA
⋮   ⋮                                         ⋮            ⋮
133 0 (0%)                                    794 (87.5%)  22 (2.4%)
134 <20                                       2094 (72%)   323 (11.1%)
135 0 (0%)                                    163 (79.5%)  <20
136 <20                                       1133 (47.4%) 372 (15.6%)
137 <20                                       986 (70.2%)  100 (7.1%)
138 0 (0%)                                    657 (62.5%)  149 (14.2%)
139 <20                                       914 (46%)    204 (10.3%)
140 <20                                       1759 (57.1%) 331 (10.8%)
141 <20                                       2619 (54.7%) 743 (15.5%)
142 0 (0%)                                    405 (64.8%)  62 (9.9%)
143 <20                                       1648 (42.7%) 492 (12.8%)
144 0 (0%)                                    121 (50.8%)  33 (13.9%)
145 0 (0%)                                    2057 (85%)   152 (6.3%)
146 0 (0%)                                    1972 (91.5%) 47 (2.2%)
147 0 (0%)                                    1113 (90%)   37 (3%)
148 0 (0%)                                    1624 (85.6%) 58 (3.1%)
149 <20                                       2925 (88.4%) 95 (2.9%)
150 <20                                       5079 (88.2%) 158 (2.7%)
151 0 (0%)                                    992 (90.8%)  20 (1.8%)
152 <20                                       2623 (81.3%) 172 (5.3%)
153 0 (0%)                                    190 (85.2%)  <20
154 <20                                       866 (36.3%)  624 (26.1%)
155 0 (0%)                                    731 (59.3%)  164 (13.3%)
156 0 (0%)                                    463 (50.1%)  186 (20.1%)
157 <20                                       688 (36.3%)  329 (17.4%)
158 <20                                       1296 (47.4%) 545 (19.9%)
159 <20                                       2167 (46.6%) 983 (21.1%)
160 0 (0%)                                    346 (59.1%)  83 (14.2%)
161 <20                                       1213 (30.6%) 943 (23.8%)
162 <20                                       90 (36.4%)   60 (24.3%)
    Median Record Depth Disability   LGBTQIA     Income <50k  Income >150k
1   114.0               834 (27.1%)  550 (17.8%) 3083 (100%)  0 (0%)
2   176.0               359 (30.9%)  144 (12.4%) 1163 (100%)  0 (0%)
3   173.0               207 (31.1%)  48 (7.2%)   665 (100%)   0 (0%)
4   175.0               557 (26.8%)  165 (7.9%)  2080 (100%)  0 (0%)
5   173.0               888 (28.8%)  331 (10.7%) 3083 (100%)  0 (0%)
6   192.0               1162 (26.5%) 454 (10.3%) 4389 (100%)  0 (0%)
7   200.5               70 (24.1%)   39 (13.4%)  290 (100%)   0 (0%)
8   127.0               1462 (30.2%) 523 (10.8%) 4834 (100%)  0 (0%)
9   102.0               95 (35.6%)   30 (11.2%)  267 (100%)   0 (0%)
10  168.0               255 (11.4%)  214 (9.6%)  0 (0%)       1447 (64.9%)
11  195.0               347 (18.8%)  113 (6.1%)  0 (0%)       1095 (59.2%)
12  190.5               139 (9.9%)   86 (6.1%)   0 (0%)       891 (63.6%)
13  217.0               292 (21.2%)  78 (5.7%)   0 (0%)       751 (54.4%)
14  198.0               528 (18.3%)  208 (7.2%)  0 (0%)       1739 (60.3%)
15  172.0               782 (12.8%)  428 (7%)    0 (0%)       3790 (62%)
16  172.0               166 (14.5%)  72 (6.3%)   0 (0%)       750 (65.6%)
17  191.0               406 (19.1%)  182 (8.5%)  0 (0%)       1188 (55.8%)
18  164.0               20 (12.1%)   <20         0 (0%)       106 (64.2%)
19     NA               NA           NA          NA           NA
20     NA               NA           NA          NA           NA
21     NA               NA           NA          NA           NA
22     NA               NA           NA          NA           NA
23     NA               NA           NA          NA           NA
24     NA               NA           NA          NA           NA
25     NA               NA           NA          NA           NA
26     NA               NA           NA          NA           NA
27     NA               NA           NA          NA           NA
28     NA               NA           NA          NA           NA
29     NA               NA           NA          NA           NA
30     NA               NA           NA          NA           NA
⋮   ⋮                   ⋮            ⋮           ⋮            ⋮
133 221.0               201 (22.2%)  59 (6.5%)   173 (19.1%)  231 (25.5%)
134 245.0               921 (31.6%)  266 (9.1%)  1181 (40.6%) 402 (13.8%)
135 193.0               43 (21%)     21 (10.2%)  65 (31.7%)   43 (21%)
136 105.0               499 (20.9%)  275 (11.5%) 1443 (60.4%) 198 (8.3%)
137 135.0               350 (24.9%)  135 (9.6%)  725 (51.6%)  192 (13.7%)
138 140.0               218 (20.7%)  64 (6.1%)   505 (48%)    133 (12.7%)
139 155.0               516 (25.9%)  131 (6.6%)  1307 (65.7%) 129 (6.5%)
140 150.0               776 (25.2%)  287 (9.3%)  1869 (60.7%) 280 (9.1%)
141 146.0               985 (20.6%)  387 (8.1%)  2529 (52.8%) 584 (12.2%)
142 127.0               123 (19.7%)  53 (8.5%)   224 (35.8%)  142 (22.7%)
143 115.0               947 (24.6%)  347 (9%)    2555 (66.3%) 192 (5%)
144 113.0               67 (28.2%)   25 (10.5%)  147 (61.8%)  <20
145 215.0               510 (21.1%)  264 (10.9%) 610 (25.2%)  642 (26.5%)
146 270.0               609 (28.2%)  144 (6.7%)  592 (27.5%)  442 (20.5%)
147 241.5               211 (17.1%)  75 (6.1%)   242 (19.6%)  387 (31.3%)
148 304.0               576 (30.3%)  81 (4.3%)   694 (36.6%)  303 (16%)
149 289.0               982 (29.7%)  194 (5.9%)  950 (28.7%)  705 (21.3%)
150 254.0               1272 (22.1%) 365 (6.3%)  1405 (24.4%) 1417 (24.6%)
151 234.0               239 (21.9%)  61 (5.6%)   198 (18.1%)  305 (27.9%)
152 269.0               1075 (33.3%) 250 (7.7%)  1125 (34.9%) 507 (15.7%)
153 268.0               57 (25.6%)   <20         56 (25.1%)   57 (25.6%)
154 100.0               478 (20%)    353 (14.8%) 1494 (62.6%) 215 (9%)
155 154.0               325 (26.4%)  115 (9.3%)  682 (55.3%)  145 (11.8%)
156 163.0               172 (18.6%)  62 (6.7%)   444 (48.1%)  142 (15.4%)
157 172.5               468 (24.7%)  156 (8.2%)  1315 (69.4%) 122 (6.4%)
158 150.0               684 (25%)    307 (11.2%) 1728 (63.3%) 258 (9.4%)
159 158.0               936 (20.1%)  441 (9.5%)  2436 (52.3%) 667 (14.3%)
160 152.0               136 (23.2%)  64 (10.9%)  228 (39%)    127 (21.7%)
161 118.0               979 (24.7%)  428 (10.8%) 2749 (69.3%) 197 (5%)
162 111.0               62 (25.1%)   34 (13.8%)  171 (69.2%)  <20
    Advanced Degree Less than HighSchool
1   0 (0%)          0 (0%)
2   0 (0%)          0 (0%)
3   0 (0%)          0 (0%)
4   0 (0%)          0 (0%)
5   0 (0%)          0 (0%)
6   0 (0%)          0 (0%)
7   0 (0%)          0 (0%)
8   0 (0%)          0 (0%)
9   0 (0%)          0 (0%)
10  0 (0%)          0 (0%)
11  0 (0%)          0 (0%)
12  0 (0%)          0 (0%)
13  0 (0%)          0 (0%)
14  0 (0%)          0 (0%)
15  0 (0%)          0 (0%)
16  0 (0%)          0 (0%)
17  0 (0%)          0 (0%)
18  0 (0%)          0 (0%)
19  NA              NA
20  NA              NA
21  NA              NA
22  NA              NA
23  NA              NA
24  NA              NA
25  NA              NA
26  NA              NA
27  NA              NA
28  NA              NA
29  NA              NA
30  NA              NA
⋮   ⋮               ⋮
133 0 (0%)          0 (0%)
134 0 (0%)          0 (0%)
135 0 (0%)          0 (0%)
136 0 (0%)          0 (0%)
137 0 (0%)          0 (0%)
138 0 (0%)          0 (0%)
139 0 (0%)          0 (0%)
140 0 (0%)          0 (0%)
141 0 (0%)          0 (0%)
142 0 (0%)          0 (0%)
143 0 (0%)          0 (0%)
144 0 (0%)          0 (0%)
145 0 (0%)          0 (0%)
146 0 (0%)          0 (0%)
147 0 (0%)          0 (0%)
148 0 (0%)          0 (0%)
149 0 (0%)          0 (0%)
150 0 (0%)          0 (0%)
151 0 (0%)          0 (0%)
152 0 (0%)          0 (0%)
153 0 (0%)          0 (0%)
154 0 (0%)          0 (0%)
155 0 (0%)          0 (0%)
156 0 (0%)          0 (0%)
157 0 (0%)          0 (0%)
158 0 (0%)          0 (0%)
159 0 (0%)          0 (0%)
160 0 (0%)          0 (0%)
161 0 (0%)          0 (0%)
162 0 (0%)          0 (0%)

# Age bucket demographics

In [25]:
merged_df <- merged_df %>%
  mutate(age_buckets = case_when(
    age <= 35 ~ "18_35",
    age <= 50 ~ "36_50",
    age <= 64 ~ "51_64",
    TRUE      ~ "65_105"
  ))

In [27]:
summarize_disease_age_buckets <- function(
  cohort,
  diseases
) {

  output_df <- data.frame()
  
  buckets <- unique(cohort$age_buckets)

  for (q in buckets) {

    stratum_df <- cohort[
      cohort$age_buckets == q & !is.na(cohort$age_buckets),
      ,
      drop = FALSE
    ]

    for (disease in diseases) {

      if (!disease %in% colnames(cohort)) next

      df <- stratum_df[
        stratum_df[[disease]] == 1 & !is.na(stratum_df[[disease]]),
        ,
        drop = FALSE
      ]

      n <- nrow(df)

      row_id <- paste(disease, q, sep = "_")
        
      output_df[row_id, "Disease"]     <- disease
      output_df[row_id, "Stratum"]     <- q
      output_df[row_id, "Sample size"] <- n

      if (n == 0) next

      # ---- Helper ----
      fmt <- function(x) {
        count <- sum(x, na.rm = TRUE)
        if (count > 0 & count < 20) return("<20")
        pct <- round(100 * count / n, 1)
        paste0(count, " (", pct, "%)")
      }

      # ---- Age ----
      output_df[row_id, "Age (median, sd)"] <- paste0(
        round(median(df$age, na.rm = TRUE), 2),
        " (", round(sd(df$age, na.rm = TRUE), 2), ")"
      )

      # ---- Sex/Gender ----
      output_df[row_id, "Cisgender Male"]   <-
        fmt(as.character(df$`sex/gender`) == "Cisgender Male")
      output_df[row_id, "Cisgender Female"] <-
        fmt(as.character(df$`sex/gender`) == "Cisgender Female")
      output_df[row_id, "SGM"]              <-
        fmt(as.character(df$`sex/gender`) == "Sexual and Gender Minority (SGM)")

      # ---- Race ----
      races <- c(
        "Asian", "Black", "Middle Eastern or North African",
        "Multiple", "Native Hawaiian or Other Pacific Islander", "White"
      )

      for (race in races) {
        output_df[row_id, race] <-
          fmt(as.character(df$`racial identity`) == race)
      }

      # ---- Ethnicity ----
      output_df[row_id, "Hispanic"] <-
        fmt(df$Hispanic == "Yes")

      # ---- Record depth ----
      output_df[row_id, "Median Record Depth"] <-
        median(df$record_depth, na.rm = TRUE)

      # ---- Disability ----
      output_df[row_id, "Disability"] <-
        if ("disability" %in% colnames(df))
          fmt(df$disability == "Yes") else NA

      # ---- LGBTQIA ----
      output_df[row_id, "LGBTQIA"] <-
        fmt(df$LGBTQIA == 1)

      # ---- Income ----
      output_df[row_id, "Income <50k"]  <-
        fmt(df$income_grouped == "<50k")
      output_df[row_id, "Income >150k"] <-
        fmt(df$income_grouped == ">150k")

      # ---- Education ----
      output_df[row_id, "Advanced Degree"] <-
        fmt(df$education == 1)
      output_df[row_id, "Less than HighSchool"] <-
        fmt(df$education == 5)
    }
  }

  output_df
}

table1 <- summarize_disease_age_buckets(
  cohort   = merged_df,
  diseases = diseases
)

save_table <- table1[order(table1$Disease),]
save_table

write_excel_csv(
  save_table,
  file.path(output_dir, "Case_age_buckets_demographics.csv")
)

                 Disease   Stratum Sample size Age (median, sd) Cisgender Male
Afib_65_105      Afib      65_105   6195       76 (6.92)        3674 (59.3%)
Afib_51_64       Afib      51_64    1505       60 (3.82)        806 (53.6%)
Afib_18_35       Afib      18_35     100       31 (3.85)        33 (33%)
Afib_36_50       Afib      36_50     422       45 (4.27)        180 (42.7%)
Asthma_65_105    Asthma    65_105   3559       72 (5.78)        1143 (32.1%)
Asthma_51_64     Asthma    51_64    3430       58 (4.02)        861 (25.1%)
Asthma_18_35     Asthma    18_35    2072       30 (4.06)        429 (20.7%)
Asthma_36_50     Asthma    36_50    3254       43 (4.22)        655 (20.1%)
BreastC_65_105   BreastC   65_105   3238       73 (5.96)        0 (0%)
BreastC_51_64    BreastC   51_64    1543       59 (3.95)        0 (0%)
BreastC_18_35    BreastC   18_35      39       33 (3.03)        0 (0%)
BreastC_36_50    BreastC   36_50     504       45 (3.93)        0 (0%)
CHD_65_105       CHD       65_105  10631       75 (6.59)        6607 (62.1%)
CHD_51_64        CHD       51_64    3399       60 (3.83)        1808 (53.2%)
CHD_18_35        CHD       18_35     109       32 (3.3)         33 (30.3%)
CHD_36_50        CHD       36_50     724       46 (4.14)        335 (46.3%)
CKD_65_105       CKD       65_105   6637       75 (7)           3345 (50.4%)
CKD_51_64        CKD       51_64    1972       59 (3.87)        791 (40.1%)
CKD_18_35        CKD       18_35     111       32 (3.47)        36 (32.4%)
CKD_36_50        CKD       36_50     538       45 (4.17)        193 (35.9%)
HyperC_65_105    HyperC    65_105  16705       73 (6.36)        7677 (46%)
HyperC_51_64     HyperC    51_64    7362       59 (3.87)        2874 (39%)
HyperC_18_35     HyperC    18_35     439       32 (3.61)        158 (36%)
HyperC_36_50     HyperC    36_50    2187       45 (4.06)        846 (38.7%)
ProstateC_65_105 ProstateC 65_105   3110       75 (6.48)        3026 (97.3%)
ProstateC_51_64  ProstateC 51_64     465       61 (3.11)        458 (98.5%)
ProstateC_18_35  ProstateC 18_35       0       NA               NA
ProstateC_36_50  ProstateC 36_50      11       49 (4.01)        <20
t1d_65_105       t1d       65_105    377       72 (5.68)        217 (57.6%)
t1d_51_64        t1d       51_64     311       59 (4.09)        132 (42.4%)
t1d_18_35        t1d       18_35     149       30 (3.94)        54 (36.2%)
t1d_36_50        t1d       36_50     261       43 (4.18)        93 (35.6%)
t2d_65_105       t2d       65_105   9193       73 (6.02)        4843 (52.7%)
t2d_51_64        t2d       51_64    5891       59 (3.94)        2295 (39%)
t2d_18_35        t2d       18_35     429       32 (3.53)        89 (20.7%)
t2d_36_50        t2d       36_50    2234       45 (4.1)         685 (30.7%)
                 Cisgender Female SGM        Asian      Black
Afib_65_105      2349 (37.9%)     172 (2.8%) 42 (0.7%)  411 (6.6%)
Afib_51_64       667 (44.3%)      32 (2.1%)  <20        304 (20.2%)
Afib_18_35       55 (55%)         <20        <20        <20
Afib_36_50       230 (54.5%)      <20        <20        83 (19.7%)
Asthma_65_105    2341 (65.8%)     75 (2.1%)  32 (0.9%)  344 (9.7%)
Asthma_51_64     2527 (73.7%)     42 (1.2%)  30 (0.9%)  760 (22.2%)
Asthma_18_35     1542 (74.4%)     101 (4.9%) 40 (1.9%)  491 (23.7%)
Asthma_36_50     2517 (77.4%)     82 (2.5%)  60 (1.8%)  717 (22%)
BreastC_65_105   3172 (98%)       66 (2%)    33 (1%)    319 (9.9%)
BreastC_51_64    1512 (98%)       31 (2%)    33 (2.1%)  224 (14.5%)
BreastC_18_35    38 (97.4%)       <20        <20        <20
BreastC_36_50    498 (98.8%)      <20        <20        82 (16.3%)
CHD_65_105       3760 (35.4%)     264 (2.5%) 114 (1.1%) 1081 (10.2%)
CHD_51_64        1517 (44.6%)     74 (2.2%)  36 (1.1%)  916 (26.9%)
CHD_18_35        74 (67.9%)       <20        0 (0%)     46 (42.2%)
CHD_36_50        368 (50.8%)      21 (2.9%)  <20        223 (30.8%)
CKD_65_105       3276 (49.4%)     <20        45 (0.7%)  1163 (17.5%)
CKD_51_64        1163 (59%)       <20        20 (1%)    784 (39.8%)
CKD_18_35        72 (64.9%)       <20        <20        41 (36.9%)
CKD_36_50        338 (62.8%)      <20        <20        215 (40%)
HyperC_65_105    8658 (51.8%)     370 (2.2%) 177 (1.1%) 1737 (10.4%)
HyperC_51_64     4378 (59.5%)     110 (1.5%) 108 (1.5%) 1516 (20.6%)
HyperC_18_35     265 (60.4%)      <20        <20        79 (18%)
HyperC_36_50     1290 (59%)       51 (2.3%)  65 (3%)    453 (20.7%)
ProstateC_65_105 0 (0%)           84 (2.7%)  20 (0.6%)  302 (9.7%)
ProstateC_51_64  0 (0%)           <20        <20        111 (23.9%)
ProstateC_18_35  NA               NA         NA         NA
ProstateC_36_50  <20              0 (0%)     <20        <20
t1d_65_105       152 (40.3%)      <20        <20        58 (15.4%)
t1d_51_64        176 (56.6%)      <20        <20        62 (19.9%)
t1d_18_35        90 (60.4%)       <20        <20        27 (18.1%)
t1d_36_50        165 (63.2%)      <20        <20        52 (19.9%)
t2d_65_105       4126 (44.9%)     224 (2.4%) 119 (1.3%) 1547 (16.8%)
t2d_51_64        3485 (59.2%)     111 (1.9%) 83 (1.4%)  1906 (32.4%)
t2d_18_35        318 (74.1%)      22 (5.1%)  <20        142 (33.1%)
t2d_36_50        1482 (66.3%)     67 (3%)    64 (2.9%)  712 (31.9%)
                 Middle Eastern or North African ⋯
Afib_65_105      20 (0.3%)                       ⋯
Afib_51_64       <20                             ⋯
Afib_18_35       0 (0%)                          ⋯
Afib_36_50       <20                             ⋯
Asthma_65_105    <20                             ⋯
Asthma_51_64     <20                             ⋯
Asthma_18_35     <20                             ⋯
Asthma_36_50     <20                             ⋯
BreastC_65_105   <20                             ⋯
BreastC_51_64    <20                             ⋯
BreastC_18_35    0 (0%)                          ⋯
BreastC_36_50    <20                             ⋯
CHD_65_105       33 (0.3%)                       ⋯
CHD_51_64        <20                             ⋯
CHD_18_35        <20                             ⋯
CHD_36_50        <20                             ⋯
CKD_65_105       21 (0.3%)                       ⋯
CKD_51_64        <20                             ⋯
CKD_18_35        <20                             ⋯
CKD_36_50        <20                             ⋯
HyperC_65_105    54 (0.3%)                       ⋯
HyperC_51_64     26 (0.4%)                       ⋯
HyperC_18_35     <20                             ⋯
HyperC_36_50     <20                             ⋯
ProstateC_65_105 <20                             ⋯
ProstateC_51_64  <20                             ⋯
ProstateC_18_35  NA                              ⋯
ProstateC_36_50  0 (0%)                          ⋯
t1d_65_105       <20                             ⋯
t1d_51_64        <20                             ⋯
t1d_18_35        <20                             ⋯
t1d_36_50        <20                             ⋯
t2d_65_105       37 (0.4%)                       ⋯
t2d_51_64        <20                             ⋯
t2d_18_35        <20                             ⋯
t2d_36_50        <20                             ⋯
                 Native Hawaiian or Other Pacific Islander White
Afib_65_105      <20                                       5279 (85.2%)
Afib_51_64       0 (0%)                                    1030 (68.4%)
Afib_18_35       0 (0%)                                    68 (68%)
Afib_36_50       0 (0%)                                    267 (63.3%)
Asthma_65_105    <20                                       2791 (78.4%)
Asthma_51_64     <20                                       2071 (60.4%)
Asthma_18_35     <20                                       1107 (53.4%)
Asthma_36_50     <20                                       1854 (57%)
BreastC_65_105   0 (0%)                                    2576 (79.6%)
BreastC_51_64    0 (0%)                                    1088 (70.5%)
BreastC_18_35    0 (0%)                                    26 (66.7%)
BreastC_36_50    0 (0%)                                    318 (63.1%)
CHD_65_105       <20                                       8306 (78.1%)
CHD_51_64        <20                                       1934 (56.9%)
CHD_18_35        0 (0%)                                    44 (40.4%)
CHD_36_50        <20                                       345 (47.7%)
CKD_65_105       <20                                       4764 (71.8%)
CKD_51_64        <20                                       894 (45.3%)
CKD_18_35        0 (0%)                                    35 (31.5%)
CKD_36_50        0 (0%)                                    195 (36.2%)
HyperC_65_105    <20                                       13019 (77.9%)
HyperC_51_64     <20                                       4636 (63%)
HyperC_18_35     0 (0%)                                    261 (59.5%)
HyperC_36_50     0 (0%)                                    1281 (58.6%)
ProstateC_65_105 0 (0%)                                    2522 (81.1%)
ProstateC_51_64  0 (0%)                                    303 (65.2%)
ProstateC_18_35  NA                                        NA
ProstateC_36_50  0 (0%)                                    <20
t1d_65_105       0 (0%)                                    281 (74.5%)
t1d_51_64        0 (0%)                                    194 (62.4%)
t1d_18_35        <20                                       93 (62.4%)
t1d_36_50        0 (0%)                                    171 (65.5%)
t2d_65_105       <20                                       6249 (68%)
t2d_51_64        <20                                       2806 (47.6%)
t2d_18_35        0 (0%)                                    163 (38%)
t2d_36_50        <20                                       944 (42.3%)
                 Hispanic    Median Record Depth Disability   LGBTQIA
Afib_65_105      239 (3.9%)  208.0               1760 (28.4%) 445 (7.2%)
Afib_51_64       123 (8.2%)  153.0               407 (27%)    137 (9.1%)
Afib_18_35       <20          75.5               31 (31%)     37 (37%)
Afib_36_50       57 (13.5%)  112.0               88 (20.9%)   58 (13.7%)
Asthma_65_105    271 (7.6%)  196.0               809 (22.7%)  262 (7.4%)
Asthma_51_64     477 (13.9%) 151.5               758 (22.1%)  330 (9.6%)
Asthma_18_35     400 (19.3%)  90.0               379 (18.3%)  544 (26.3%)
Asthma_36_50     540 (16.6%) 125.0               661 (20.3%)  492 (15.1%)
BreastC_65_105   192 (5.9%)  188.0               625 (19.3%)  182 (5.6%)
BreastC_51_64    165 (10.7%) 155.0               287 (18.6%)  108 (7%)
BreastC_18_35    <20         162.0               <20          <20
BreastC_36_50    82 (16.3%)  147.0               71 (14.1%)   42 (8.3%)
CHD_65_105       694 (6.5%)  217.0               3019 (28.4%) 750 (7.1%)
CHD_51_64        416 (12.2%) 166.0               905 (26.6%)  378 (11.1%)
CHD_18_35        <20         117.0               20 (18.3%)   25 (22.9%)
CHD_36_50        131 (18.1%) 128.0               162 (22.4%)  103 (14.2%)
CKD_65_105       401 (6%)    216.0               1930 (29.1%) 297 (4.5%)
CKD_51_64        235 (11.9%) 167.0               524 (26.6%)  177 (9%)
CKD_18_35        32 (28.8%)  133.0               <20          22 (19.8%)
CKD_36_50        103 (19.1%) 152.0               113 (21%)    71 (13.2%)
HyperC_65_105    1130 (6.8%) 202.0               3639 (21.8%) 1111 (6.7%)
HyperC_51_64     893 (12.1%) 157.0               1489 (20.2%) 689 (9.4%)
HyperC_18_35     79 (18%)     89.0               87 (19.8%)   95 (21.6%)
HyperC_36_50     338 (15.5%) 125.0               438 (20%)    275 (12.6%)
ProstateC_65_105 133 (4.3%)  189.5               744 (23.9%)  225 (7.2%)
ProstateC_51_64  40 (8.6%)   120.0               71 (15.3%)   57 (12.3%)
ProstateC_18_35  NA             NA               NA           NA
ProstateC_36_50  <20         147.0               <20          0 (0%)
t1d_65_105       22 (5.8%)   232.0               127 (33.7%)  28 (7.4%)
t1d_51_64        42 (13.5%)  159.0               86 (27.7%)   27 (8.7%)
t1d_18_35        22 (14.8%)   71.0               23 (15.4%)   33 (22.1%)
t1d_36_50        38 (14.6%)  136.0               67 (25.7%)   31 (11.9%)
t2d_65_105       898 (9.8%)  195.0               2821 (30.7%) 688 (7.5%)
t2d_51_64        952 (16.2%) 144.0               1651 (28%)   601 (10.2%)
t2d_18_35        91 (21.2%)   92.0               100 (23.3%)  99 (23.1%)
t2d_36_50        468 (20.9%) 111.0               553 (24.8%)  314 (14.1%)
                 Income <50k  Income >150k Advanced Degree Less than HighSchool
Afib_65_105      2395 (38.7%) 838 (13.5%)  0 (0%)          0 (0%)
Afib_51_64       740 (49.2%)  279 (18.5%)  0 (0%)          0 (0%)
Afib_18_35       55 (55%)     <20          0 (0%)          0 (0%)
Afib_36_50       220 (52.1%)  65 (15.4%)   0 (0%)          0 (0%)
Asthma_65_105    1274 (35.8%) 546 (15.3%)  0 (0%)          0 (0%)
Asthma_51_64     1613 (47%)   593 (17.3%)  0 (0%)          0 (0%)
Asthma_18_35     1360 (65.6%) 128 (6.2%)   0 (0%)          0 (0%)
Asthma_36_50     1688 (51.9%) 445 (13.7%)  0 (0%)          0 (0%)
BreastC_65_105   1242 (38.4%) 476 (14.7%)  0 (0%)          0 (0%)
BreastC_51_64    521 (33.8%)  383 (24.8%)  0 (0%)          0 (0%)
BreastC_18_35    <20          <20          0 (0%)          0 (0%)
BreastC_36_50    165 (32.7%)  133 (26.4%)  0 (0%)          0 (0%)
CHD_65_105       4552 (42.8%) 1358 (12.8%) 0 (0%)          0 (0%)
CHD_51_64        2103 (61.9%) 448 (13.2%)  0 (0%)          0 (0%)
CHD_18_35        86 (78.9%)   <20          0 (0%)          0 (0%)
CHD_36_50        519 (71.7%)  52 (7.2%)    0 (0%)          0 (0%)
CKD_65_105       3353 (50.5%) 606 (9.1%)   0 (0%)          0 (0%)
CKD_51_64        1256 (63.7%) 175 (8.9%)   0 (0%)          0 (0%)
CKD_18_35        89 (80.2%)   <20          0 (0%)          0 (0%)
CKD_36_50        383 (71.2%)  33 (6.1%)    0 (0%)          0 (0%)
HyperC_65_105    6588 (39.4%) 2413 (14.4%) 0 (0%)          0 (0%)
HyperC_51_64     3375 (45.8%) 1364 (18.5%) 0 (0%)          0 (0%)
HyperC_18_35     251 (57.2%)  30 (6.8%)    0 (0%)          0 (0%)
HyperC_36_50     1026 (46.9%) 360 (16.5%)  0 (0%)          0 (0%)
ProstateC_65_105 893 (28.7%)  642 (20.6%)  0 (0%)          0 (0%)
ProstateC_51_64  144 (31%)    142 (30.5%)  0 (0%)          0 (0%)
ProstateC_18_35  NA           NA           NA              NA
ProstateC_36_50  <20          <20          0 (0%)          0 (0%)
t1d_65_105       162 (43%)    36 (9.5%)    0 (0%)          0 (0%)
t1d_51_64        149 (47.9%)  48 (15.4%)   0 (0%)          0 (0%)
t1d_18_35        90 (60.4%)   <20          0 (0%)          0 (0%)
t1d_36_50        133 (51%)    32 (12.3%)   0 (0%)          0 (0%)
t2d_65_105       4612 (50.2%) 746 (8.1%)   0 (0%)          0 (0%)
t2d_51_64        3639 (61.8%) 485 (8.2%)   0 (0%)          0 (0%)
t2d_18_35        341 (79.5%)  <20          0 (0%)          0 (0%)
t2d_36_50        1483 (66.4%) 135 (6%)     0 (0%)          0 (0%)

# Richer SDoH survey Quintile demographics

In [28]:
# variables to reverse-code
to_flip <- c(
  "Health Coverage", "Health Literacy", "Healthcare Utilization",
  "Housing Quality", "Own Home", "Respect", "Social Cohesion",
  "Social Support", "Spiritual Experiences", "Walkability"
)

# -------------------------------------------------
# 1. Flip binary coding: 1 -> 0, 0 -> 1
# -------------------------------------------------
sdoh_survey_data_case_control[to_flip] <- lapply(
  sdoh_survey_data_case_control[to_flip],
  function(x) ifelse(is.na(x), NA, 1 - x)
)

# -------------------------------------------------
# 2. Rename variables after flipping
# -------------------------------------------------
new_names <- c(
  "No Health Coverage",
  "Low Health Literacy",
  "Low Healthcare Utilization",
  "Low Housing Quality",
  "No Own Home",
  "Low Respect",
  "Low Social Cohesion",
  "Low Social Support",
  "Low Spiritual Experiences",
  "Low Walkability"
)

sdoh_var <-c('No Own Home', 'Low Health Literacy', 'Low Housing Quality', 'Housing Instability',
             'Food Insecurity', 'Low Walkability', 'Loneliness', 'Crime', 'Physical Disorder', 'Social Disorder',
             'Everyday Discrimination', 'Medical Discrimination', 'Low Social Cohesion', 'Stress', 
             'Low Social Support', 'Low Spiritual Experiences', 'No Health Coverage', 'Low Healthcare Utilization',
             'Delayed Care', 'Can\'t afford care', 'Worried Pay', 'Low Respect'
)

names(sdoh_survey_data_case_control)[match(to_flip, names(sdoh_survey_data_case_control))] <- new_names

# -------------------------------------------------
# 3. Handle Binary Variables
# -------------------------------------------------

binary_vars <- c("Food Insecurity", "Can't afford care", "Housing Instability", "Low Health Literacy", 
                "Delayed Care", "Low Housing Quality", "No Health Coverage", "No Own Home")
       
sdoh_survey_data_case_control[, binary_vars] <- lapply(
  sdoh_survey_data_case_control[, binary_vars],
  function(x) as.numeric(
    ifelse(is.na(x), NA, ifelse(x < 0.5, 0, 1))
  )
)
              
# -------------------------------------------------
# 3. Z score continous variables
# -------------------------------------------------
       
continious_vars <- setdiff(sdoh_var, binary_vars)

sdoh_survey_data_case_control[continious_vars] <- lapply(
  sdoh_survey_data_case_control[continious_vars],
  function(x) as.numeric(scale(ifelse(is.na(x), NA, x)))
)
       
# -------------------------------------------------
# 4. Compute Q1 and Q5
# -------------------------------------------------

#Compute Q1 and Q5
quantiles <- sdoh_survey_data_case_control %>%
  pivot_longer(
    cols = all_of(sdoh_var),
    names_to = "domain",
    values_to = "value"
  ) %>%
  group_by(domain) %>%
  summarize(
    q1 = if (dplyr::n_distinct(stats::na.omit(value)) <= 2) {
      min(value, na.rm = TRUE)
    } else {
      round(as.numeric(stats::quantile(value, 0.20, na.rm = TRUE)), 3)
    },

    q5 = if (dplyr::n_distinct(stats::na.omit(value)) <= 2) {
      max(value, na.rm = TRUE)
    } else {
      round(as.numeric(stats::quantile(value, 0.80, na.rm = TRUE)), 3)
    },
    .groups = "drop"
  )



#Add Q1 / Q5 indicator columns back to original data
for (v in sdoh_var) {
  q1_val <- quantiles$q1[quantiles$domain == v]
  q5_val <- quantiles$q5[quantiles$domain == v]

  sdoh_survey_data_case_control[[paste0(v, "_Q1")]] <- sdoh_survey_data_case_control[[v]] <= q1_val
  sdoh_survey_data_case_control[[paste0(v, "_Q5")]] <- sdoh_survey_data_case_control[[v]] >= q5_val
}

In [29]:
table2 <- summarize_disease_sdoh_quintiles(
  cohort   = sdoh_survey_data_case_control,
  diseases = diseases_short,
  sdoh_vars = sdoh_var
)

table2 
    
#Save
write_excel_csv(
  table2,
  file.path(output_dir, "Case_richer_SDoH_quintiles_demographics.csv")
)

    SDoH                Stratum Disease Sample size Age (median, sd)
1   No Own Home         Q1      Asthma   3735       63 (13.8)
2   No Own Home         Q1      Afib     3205       73 (10.09)
3   No Own Home         Q1      CKD      2796       73 (9.46)
4   No Own Home         Q1      CHD      4837       73 (8.7)
5   No Own Home         Q1      HyperC  10186       70 (10.31)
6   No Own Home         Q1      t2d      5068       69 (10.63)
7   No Own Home         Q5      Asthma   1822       47 (15.51)
8   No Own Home         Q5      Afib      838       69 (14.18)
9   No Own Home         Q5      CKD      1003       69 (12.42)
10  No Own Home         Q5      CHD      1437       69 (11.67)
11  No Own Home         Q5      HyperC   2697       65 (13.43)
12  No Own Home         Q5      t2d      2510       61 (12.58)
13  Low Health Literacy Q1      Asthma   4366       59 (15.1)
14  Low Health Literacy Q1      Afib     3039       72 (10.97)
15  Low Health Literacy Q1      CKD      2725       72 (10.38)
16  Low Health Literacy Q1      CHD      4604       72 (9.36)
17  Low Health Literacy Q1      HyperC  10067       69 (10.93)
18  Low Health Literacy Q1      t2d      5337       67 (11.57)
19  Low Health Literacy Q5      Asthma   1191       56 (16.4)
20  Low Health Literacy Q5      Afib     1004       73 (11.95)
21  Low Health Literacy Q5      CKD      1074       73 (10.9)
22  Low Health Literacy Q5      CHD      1670       72 (10.36)
23  Low Health Literacy Q5      HyperC   2816       69 (12.11)
24  Low Health Literacy Q5      t2d      2241       67 (12.2)
25  Low Housing Quality Q1      Asthma   4260       60 (15.01)
26  Low Housing Quality Q1      Afib     3380       73 (10.58)
27  Low Housing Quality Q1      CKD      3143       73 (10.28)
28  Low Housing Quality Q1      CHD      5281       72 (9.28)
29  Low Housing Quality Q1      HyperC  10776       70 (10.86)
30  Low Housing Quality Q1      t2d      6007       68 (11.39)
⋮   ⋮                   ⋮       ⋮       ⋮           ⋮
235 Can't afford care   Q5      Asthma  2479        54 (15.16)
236 Can't afford care   Q5      Afib    1387        70 (12)
237 Can't afford care   Q5      CKD     1314        70 (10.83)
238 Can't afford care   Q5      CHD     2072        70 (10.21)
239 Can't afford care   Q5      HyperC  4167        67 (11.75)
240 Can't afford care   Q5      t2d     3130        64 (12.03)
241 Worried Pay         Q1      Asthma     0        NA
242 Worried Pay         Q1      Afib       0        NA
243 Worried Pay         Q1      CKD        0        NA
244 Worried Pay         Q1      CHD        0        NA
245 Worried Pay         Q1      HyperC     0        NA
246 Worried Pay         Q1      t2d        0        NA
247 Worried Pay         Q5      Asthma  2613        53 (14.85)
248 Worried Pay         Q5      Afib    1276        68 (12.36)
249 Worried Pay         Q5      CKD     1281        69 (11.18)
250 Worried Pay         Q5      CHD     1930        69 (10.3)
251 Worried Pay         Q5      HyperC  4433        65 (11.68)
252 Worried Pay         Q5      t2d     3180        63 (11.85)
253 Low Respect         Q1      Asthma     0        NA
254 Low Respect         Q1      Afib       0        NA
255 Low Respect         Q1      CKD        0        NA
256 Low Respect         Q1      CHD        0        NA
257 Low Respect         Q1      HyperC     0        NA
258 Low Respect         Q1      t2d        0        NA
259 Low Respect         Q5      Asthma  1054        50 (15.29)
260 Low Respect         Q5      Afib     578        68 (14.11)
261 Low Respect         Q5      CKD      488        70 (11.58)
262 Low Respect         Q5      CHD      871        70 (10.84)
263 Low Respect         Q5      HyperC  1740        65 (12.36)
264 Low Respect         Q5      t2d     1211        63 (12.74)
    Cisgender Male Cisgender Female SGM        Asian      Black       ⋯
1   1030 (27.6%)   2656 (71.1%)     49 (1.3%)  46 (1.2%)  178 (4.8%)  ⋯
2   1889 (58.9%)   1242 (38.8%)     74 (2.3%)  <20        103 (3.2%)  ⋯
3   1397 (50%)     1395 (49.9%)     <20        26 (0.9%)  266 (9.5%)  ⋯
4   3081 (63.7%)   1662 (34.4%)     94 (1.9%)  36 (0.7%)  179 (3.7%)  ⋯
5   4570 (44.9%)   5473 (53.7%)     143 (1.4%) 116 (1.1%) 494 (4.8%)  ⋯
6   2622 (51.7%)   2373 (46.8%)     73 (1.4%)  78 (1.5%)  461 (9.1%)  ⋯
7   354 (19.4%)    1387 (76.1%)     81 (4.4%)  24 (1.3%)  354 (19.4%) ⋯
8   394 (47%)      419 (50%)        25 (3%)    <20        106 (12.6%) ⋯
9   432 (43.1%)    567 (56.5%)      <20        <20        275 (27.4%) ⋯
10  750 (52.2%)    655 (45.6%)      32 (2.2%)  <20        229 (15.9%) ⋯
11  1054 (39.1%)   1581 (58.6%)     62 (2.3%)  29 (1.1%)  447 (16.6%) ⋯
12  936 (37.3%)    1494 (59.5%)     80 (3.2%)  36 (1.4%)  627 (25%)   ⋯
13  1058 (24.2%)   3219 (73.7%)     89 (2%)    56 (1.3%)  361 (8.3%)  ⋯
14  1644 (54.1%)   1320 (43.4%)     75 (2.5%)  20 (0.7%)  145 (4.8%)  ⋯
15  1243 (45.6%)   1477 (54.2%)     <20        22 (0.8%)  354 (13%)   ⋯
16  2739 (59.5%)   1780 (38.7%)     85 (1.8%)  34 (0.7%)  264 (5.7%)  ⋯
17  4209 (41.8%)   5707 (56.7%)     151 (1.5%) 109 (1.1%) 640 (6.4%)  ⋯
18  2407 (45.1%)   2832 (53.1%)     98 (1.8%)  80 (1.5%)  697 (13.1%) ⋯
19  326 (27.4%)    824 (69.2%)      41 (3.4%)  <20        171 (14.4%) ⋯
20  639 (63.6%)    341 (34%)        24 (2.4%)  <20        64 (6.4%)   ⋯
21  586 (54.6%)    485 (45.2%)      <20        <20        187 (17.4%) ⋯
22  1092 (65.4%)   537 (32.2%)      41 (2.5%)  <20        144 (8.6%)  ⋯
23  1415 (50.2%)   1347 (47.8%)     54 (1.9%)  36 (1.3%)  301 (10.7%) ⋯
24  1151 (51.4%)   1035 (46.2%)     55 (2.5%)  34 (1.5%)  391 (17.4%) ⋯
25  1126 (26.4%)   3066 (72%)       68 (1.6%)  52 (1.2%)  356 (8.4%)  ⋯
26  1973 (58.4%)   1331 (39.4%)     76 (2.2%)  20 (0.6%)  155 (4.6%)  ⋯
27  1556 (49.5%)   1580 (50.3%)     <20        30 (1%)    374 (11.9%) ⋯
28  3327 (63%)     1851 (35.1%)     103 (2%)   38 (0.7%)  292 (5.5%)  ⋯
29  4832 (44.8%)   5791 (53.7%)     153 (1.4%) 128 (1.2%) 687 (6.4%)  ⋯
30  2958 (49.2%)   2942 (49%)       107 (1.8%) 96 (1.6%)  795 (13.2%) ⋯
⋮   ⋮              ⋮                ⋮          ⋮          ⋮           ⋱
235 454 (18.3%)    1945 (78.5%)     80 (3.2%)  31 (1.3%)  273 (11%)   ⋯
236 641 (46.2%)    709 (51.1%)      37 (2.7%)  <20        92 (6.6%)   ⋯
237 522 (39.7%)    790 (60.1%)      <20        <20        230 (17.5%) ⋯
238 1097 (52.9%)   936 (45.2%)      39 (1.9%)  <20        183 (8.8%)  ⋯
239 1525 (36.6%)   2566 (61.6%)     76 (1.8%)  41 (1%)    375 (9%)    ⋯
240 1223 (39.1%)   1837 (58.7%)     70 (2.2%)  39 (1.2%)  499 (15.9%) ⋯
241 NA             NA               NA         NA         NA          ⋯
242 NA             NA               NA         NA         NA          ⋯
243 NA             NA               NA         NA         NA          ⋯
244 NA             NA               NA         NA         NA          ⋯
245 NA             NA               NA         NA         NA          ⋯
246 NA             NA               NA         NA         NA          ⋯
247 461 (17.6%)    2076 (79.4%)     76 (2.9%)  37 (1.4%)  250 (9.6%)  ⋯
248 542 (42.5%)    696 (54.5%)      38 (3%)    <20        76 (6%)     ⋯
249 476 (37.2%)    803 (62.7%)      <20        <20        206 (16.1%) ⋯
250 958 (49.6%)    931 (48.2%)      41 (2.1%)  <20        155 (8%)    ⋯
251 1488 (33.6%)   2869 (64.7%)     76 (1.7%)  60 (1.4%)  359 (8.1%)  ⋯
252 1207 (38%)     1900 (59.7%)     73 (2.3%)  55 (1.7%)  446 (14%)   ⋯
253 NA             NA               NA         NA         NA          ⋯
254 NA             NA               NA         NA         NA          ⋯
255 NA             NA               NA         NA         NA          ⋯
256 NA             NA               NA         NA         NA          ⋯
257 NA             NA               NA         NA         NA          ⋯
258 NA             NA               NA         NA         NA          ⋯
259 184 (17.5%)    830 (78.7%)      40 (3.8%)  <20        98 (9.3%)   ⋯
260 231 (40%)      322 (55.7%)      25 (4.3%)  <20        47 (8.1%)   ⋯
261 191 (39.1%)    296 (60.7%)      <20        <20        104 (21.3%) ⋯
262 446 (51.2%)    399 (45.8%)      26 (3%)    <20        82 (9.4%)   ⋯
263 639 (36.7%)    1054 (60.6%)     47 (2.7%)  <20        165 (9.5%)  ⋯
264 432 (35.7%)    741 (61.2%)      38 (3.1%)  20 (1.7%)  197 (16.3%) ⋯
    Native Hawaiian or Other Pacific Islander White        Hispanic
1   0 (0%)                                    3219 (86.2%) 187 (5%)
2   <20                                       2933 (91.5%) 59 (1.8%)
3   <20                                       2333 (83.4%) 76 (2.7%)
4   <20                                       4333 (89.6%) 134 (2.8%)
5   <20                                       8923 (87.6%) 324 (3.2%)
6   <20                                       4076 (80.4%) 298 (5.9%)
7   <20                                       1150 (63.1%) 245 (13.4%)
8   0 (0%)                                    644 (76.8%)  50 (6%)
9   0 (0%)                                    612 (61%)    74 (7.4%)
10  0 (0%)                                    1011 (70.4%) 119 (8.3%)
11  <20                                       1850 (68.6%) 270 (10%)
12  <20                                       1357 (54.1%) 401 (16%)
13  0 (0%)                                    3553 (81.4%) 284 (6.5%)
14  <20                                       2735 (90%)   62 (2%)
15  0 (0%)                                    2187 (80.3%) 77 (2.8%)
16  <20                                       4017 (87.3%) 137 (3%)
17  <20                                       8660 (86%)   365 (3.6%)
18  <20                                       4027 (75.5%) 371 (7%)
19  <20                                       816 (68.5%)  148 (12.4%)
20  0 (0%)                                    842 (83.9%)  47 (4.7%)
21  <20                                       758 (70.6%)  73 (6.8%)
22  0 (0%)                                    1327 (79.5%) 116 (6.9%)
23  <20                                       2113 (75%)   229 (8.1%)
24  <20                                       1406 (62.7%) 328 (14.6%)
25  0 (0%)                                    3441 (80.8%) 289 (6.8%)
26  <20                                       3030 (89.6%) 79 (2.3%)
27  0 (0%)                                    2517 (80.1%) 111 (3.5%)
28  <20                                       4575 (86.6%) 196 (3.7%)
29  <20                                       9164 (85%)   461 (4.3%)
30  <20                                       4403 (73.3%) 531 (8.8%)
⋮   ⋮                                         ⋮            ⋮
235 <20                                       1871 (75.5%) 223 (9%)
236 0 (0%)                                    1206 (87%)   47 (3.4%)
237 0 (0%)                                    970 (73.8%)  58 (4.4%)
238 0 (0%)                                    1701 (82.1%) 98 (4.7%)
239 <20                                       3371 (80.9%) 229 (5.5%)
240 0 (0%)                                    2162 (69.1%) 341 (10.9%)
241 NA                                        NA           NA
242 NA                                        NA           NA
243 NA                                        NA           NA
244 NA                                        NA           NA
245 NA                                        NA           NA
246 NA                                        NA           NA
247 <20                                       2014 (77.1%) 251 (9.6%)
248 0 (0%)                                    1116 (87.5%) 54 (4.2%)
249 0 (0%)                                    959 (74.9%)  72 (5.6%)
250 0 (0%)                                    1597 (82.7%) 109 (5.6%)
251 <20                                       3590 (81%)   286 (6.5%)
252 <20                                       2185 (68.7%) 403 (12.7%)
253 NA                                        NA           NA
254 NA                                        NA           NA
255 NA                                        NA           NA
256 NA                                        NA           NA
257 NA                                        NA           NA
258 NA                                        NA           NA
259 0 (0%)                                    814 (77.2%)  97 (9.2%)
260 0 (0%)                                    495 (85.6%)  24 (4.2%)
261 0 (0%)                                    341 (69.9%)  <20
262 0 (0%)                                    705 (80.9%)  39 (4.5%)
263 0 (0%)                                    1387 (79.7%) 107 (6.1%)
264 0 (0%)                                    820 (67.7%)  131 (10.8%)
    Median Record Depth Disability   LGBTQIA     Income <50k  Income >150k
1   160.0               806 (21.6%)  354 (9.5%)  694 (18.6%)  953 (25.5%)
2   173.0               950 (29.6%)  205 (6.4%)  701 (21.9%)  657 (20.5%)
3   205.0               906 (32.4%)  130 (4.6%)  809 (28.9%)  428 (15.3%)
4   192.0               1476 (30.5%) 320 (6.6%)  1062 (22%)   1018 (21%)
5   172.0               2167 (21.3%) 706 (6.9%)  2101 (20.6%) 2388 (23.4%)
6   177.0               1664 (32.8%) 387 (7.6%)  1395 (27.5%) 757 (14.9%)
7   155.0               745 (40.9%)  370 (20.3%) 1142 (62.7%) 108 (5.9%)
8   189.5               369 (44%)    121 (14.4%) 508 (60.6%)  63 (7.5%)
9   224.0               488 (48.7%)  88 (8.8%)   711 (70.9%)  37 (3.7%)
10  227.0               689 (47.9%)  188 (13.1%) 993 (69.1%)  61 (4.2%)
11  206.0               1040 (38.6%) 342 (12.7%) 1687 (62.6%) 166 (6.2%)
12  180.5               1179 (47%)   358 (14.3%) 1834 (73.1%) 57 (2.3%)
13  154.0               1008 (23.1%) 525 (12%)   1207 (27.6%) 939 (21.5%)
14  174.0               857 (28.2%)  249 (8.2%)  792 (26.1%)  621 (20.4%)
15  198.0               868 (31.9%)  165 (6.1%)  952 (34.9%)  405 (14.9%)
16  194.0               1369 (29.7%) 369 (8%)    1292 (28.1%) 937 (20.4%)
17  172.0               2085 (20.7%) 784 (7.8%)  2499 (24.8%) 2263 (22.5%)
18  175.0               1706 (32%)   521 (9.8%)  1928 (36.1%) 697 (13.1%)
19  170.0               543 (45.6%)  199 (16.7%) 629 (52.8%)  122 (10.2%)
20  181.0               462 (46%)    77 (7.7%)   417 (41.5%)  99 (9.9%)
21  247.0               526 (49%)    53 (4.9%)   568 (52.9%)  60 (5.6%)
22  220.0               796 (47.7%)  139 (8.3%)  763 (45.7%)  142 (8.5%)
23  203.0               1122 (39.8%) 264 (9.4%)  1289 (45.8%) 291 (10.3%)
24  187.0               1137 (50.7%) 224 (10%)   1301 (58.1%) 117 (5.2%)
25  161.0               1031 (24.2%) 460 (10.8%) 1182 (27.7%) 924 (21.7%)
26  177.0               1015 (30%)   248 (7.3%)  877 (25.9%)  640 (18.9%)
27  209.0               1097 (34.9%) 168 (5.3%)  1118 (35.6%) 423 (13.5%)
28  199.0               1703 (32.2%) 406 (7.7%)  1547 (29.3%) 964 (18.3%)
29  176.0               2430 (22.6%) 795 (7.4%)  2771 (25.7%) 2308 (21.4%)
30  180.0               2064 (34.4%) 524 (8.7%)  2257 (37.6%) 719 (12%)
⋮   ⋮                   ⋮            ⋮           ⋮            ⋮
235 144.0               892 (36%)    394 (15.9%) 1121 (45.2%) 257 (10.4%)
236 163.0               534 (38.5%)  134 (9.7%)  620 (44.7%)  147 (10.6%)
237 205.5               565 (43%)    83 (6.3%)   730 (55.6%)  83 (6.3%)
238 205.5               916 (44.2%)  199 (9.6%)  1013 (48.9%) 191 (9.2%)
239 183.0               1365 (32.8%) 405 (9.7%)  1832 (44%)   446 (10.7%)
240 167.0               1386 (44.3%) 379 (12.1%) 1758 (56.2%) 162 (5.2%)
241    NA               NA           NA          NA           NA
242    NA               NA           NA          NA           NA
243    NA               NA           NA          NA           NA
244    NA               NA           NA          NA           NA
245    NA               NA           NA          NA           NA
246    NA               NA           NA          NA           NA
247 145.0               881 (33.7%)  404 (15.5%) 1068 (40.9%) 282 (10.8%)
248 153.5               467 (36.6%)  127 (10%)   550 (43.1%)  116 (9.1%)
249 187.0               515 (40.2%)  79 (6.2%)   694 (54.2%)  76 (5.9%)
250 183.0               808 (41.9%)  185 (9.6%)  954 (49.4%)  156 (8.1%)
251 165.0               1321 (29.8%) 442 (10%)   1830 (41.3%) 464 (10.5%)
252 161.0               1259 (39.6%) 371 (11.7%) 1643 (51.7%) 179 (5.6%)
253    NA               NA           NA          NA           NA
254    NA               NA           NA          NA           NA
255    NA               NA           NA          NA           NA
256    NA               NA           NA          NA           NA
257    NA               NA           NA          NA           NA
258    NA               NA           NA          NA           NA
259 146.0               420 (39.8%)  211 (20%)   462 (43.8%)  156 (14.8%)
260 143.5               242 (41.9%)  68 (11.8%)  233 (40.3%)  74 (12.8%)
261 192.0               223 (45.7%)  30 (6.1%)   243 (49.8%)  38 (7.8%)
262 193.0               374 (42.9%)  83 (9.5%)   357 (41%)    121 (13.9%)
263 176.0               577 (33.2%)  177 (10.2%) 661 (38%)    266 (15.3%)
264 159.0               553 (45.7%)  153 (12.6%) 624 (51.5%)  105 (8.7%)
    Advanced Degree Less than HighSchool
1   0 (0%)          0 (0%)
2   0 (0%)          0 (0%)
3   0 (0%)          0 (0%)
4   0 (0%)          0 (0%)
5   0 (0%)          0 (0%)
6   0 (0%)          0 (0%)
7   0 (0%)          0 (0%)
8   0 (0%)          0 (0%)
9   0 (0%)          0 (0%)
10  0 (0%)          0 (0%)
11  0 (0%)          0 (0%)
12  0 (0%)          0 (0%)
13  0 (0%)          0 (0%)
14  0 (0%)          0 (0%)
15  0 (0%)          0 (0%)
16  0 (0%)          0 (0%)
17  0 (0%)          0 (0%)
18  0 (0%)          0 (0%)
19  0 (0%)          0 (0%)
20  0 (0%)          0 (0%)
21  0 (0%)          0 (0%)
22  0 (0%)          0 (0%)
23  0 (0%)          0 (0%)
24  0 (0%)          0 (0%)
25  0 (0%)          0 (0%)
26  0 (0%)          0 (0%)
27  0 (0%)          0 (0%)
28  0 (0%)          0 (0%)
29  0 (0%)          0 (0%)
30  0 (0%)          0 (0%)
⋮   ⋮               ⋮
235 0 (0%)          0 (0%)
236 0 (0%)          0 (0%)
237 0 (0%)          0 (0%)
238 0 (0%)          0 (0%)
239 0 (0%)          0 (0%)
240 0 (0%)          0 (0%)
241 NA              NA
242 NA              NA
243 NA              NA
244 NA              NA
245 NA              NA
246 NA              NA
247 0 (0%)          0 (0%)
248 0 (0%)          0 (0%)
249 0 (0%)          0 (0%)
250 0 (0%)          0 (0%)
251 0 (0%)          0 (0%)
252 0 (0%)          0 (0%)
253 NA              NA
254 NA              NA
255 NA              NA
256 NA              NA
257 NA              NA
258 NA              NA
259 0 (0%)          0 (0%)
260 0 (0%)          0 (0%)
261 0 (0%)          0 (0%)
262 0 (0%)          0 (0%)
263 0 (0%)          0 (0%)
264 0 (0%)          0 (0%)